-- New opportunities added 28 Sept 2026.
-- RSM UK was already tracked (47 grad_scheme rows), but only for the graduate
-- programme. The founder pointed out RSM's own careers site also lists
-- Placement (sandwich-year) and School/College Leaver routes that were not
-- tracked at all - 24 Placement roles and 51 School Leaver roles (including
-- FastTrack Audit, Audit Data Analytics, and Consulting AAT/CMDA/CMD
-- variants), none of which existed in the database under any category.
-- Already applied directly to production via the Supabase admin client -
-- this file is kept for the repo's audit trail.

insert into public.opportunities
  (company, role_title, category, region, city, country, cycle_year, status,
   deadline, apply_url, notes, visa_sponsorship, sponsorship_verified_at, is_published)
values
  ('RSM UK', 'Audit Placement - Aberdeen - September 2027', 'placement_year', 'uk', 'Aberdeen', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec92',
   $q$12-month paid placement in Audit as part of a sandwich degree, Aberdeen. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Belfast - September 2027', 'placement_year', 'uk', 'Belfast', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec100',
   $q$12-month paid placement in Audit as part of a sandwich degree, Belfast. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Birmingham - September 2027', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec175',
   $q$12-month paid placement in Audit as part of a sandwich degree, Birmingham. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Bristol - September 2027', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec176',
   $q$12-month paid placement in Audit as part of a sandwich degree, Bristol. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Gatwick - September 2027', 'placement_year', 'uk', 'Crawley', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec194',
   $q$12-month paid placement in Audit as part of a sandwich degree, Crawley. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Guildford - September 2027', 'placement_year', 'uk', 'Guildford', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec196',
   $q$12-month paid placement in Audit as part of a sandwich degree, Guildford. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Hull - September 2027', 'placement_year', 'uk', 'Hull', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec113',
   $q$12-month paid placement in Audit as part of a sandwich degree, Hull. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Leeds - September 2027', 'placement_year', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec117',
   $q$12-month paid placement in Audit as part of a sandwich degree, Leeds. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Liverpool - September 2027', 'placement_year', 'uk', 'Liverpool', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec64',
   $q$12-month paid placement in Audit as part of a sandwich degree, Liverpool. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - London - September 2027', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec199',
   $q$12-month paid placement in Audit as part of a sandwich degree, London. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Manchester - September 2027', 'placement_year', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec68',
   $q$12-month paid placement in Audit as part of a sandwich degree, Manchester. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Milton Keynes - September 2027', 'placement_year', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec185',
   $q$12-month paid placement in Audit as part of a sandwich degree, Milton Keynes. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Newcastle - September 2027', 'placement_year', 'uk', 'Newcastle', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec119',
   $q$12-month paid placement in Audit as part of a sandwich degree, Newcastle. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Nottingham - September 2027', 'placement_year', 'uk', 'Nottingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec189',
   $q$12-month paid placement in Audit as part of a sandwich degree, Nottingham. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Preston - September 2027', 'placement_year', 'uk', 'Preston', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec73',
   $q$12-month paid placement in Audit as part of a sandwich degree, Preston. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Reading - September 2027', 'placement_year', 'uk', 'Reading', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec202',
   $q$12-month paid placement in Audit as part of a sandwich degree, Reading. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Southampton - September 2027', 'placement_year', 'uk', 'Southampton', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec204',
   $q$12-month paid placement in Audit as part of a sandwich degree, Southampton. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Placement - Stoke - September 2027', 'placement_year', 'uk', 'Stoke On Trent', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec283',
   $q$12-month paid placement in Audit as part of a sandwich degree, Stoke On Trent. Real client work with on-the-job training and internal courses; strong performers can progress to RSM's graduate programme. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting Placement - Birmingham - September 2027', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec127',
   $q$12-month paid placement in Consulting as part of a sandwich degree, Birmingham, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting Placement - Bristol - September 2027', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec137',
   $q$12-month paid placement in Consulting as part of a sandwich degree, Bristol, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting Placement - Leeds - September 2027', 'placement_year', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec133',
   $q$12-month paid placement in Consulting as part of a sandwich degree, Leeds, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting Placement - Liverpool - September 2027', 'placement_year', 'uk', 'Liverpool', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec135',
   $q$12-month paid placement in Consulting as part of a sandwich degree, Liverpool, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax Placement - Birmingham - September 2027', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec62',
   $q$12-month paid placement in Tax as part of a sandwich degree, Birmingham. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax Placement - Nottingham - September 2027', 'placement_year', 'uk', 'Nottingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec81',
   $q$12-month paid placement in Tax as part of a sandwich degree, Nottingham. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Aberdeen - September 2027', 'apprenticeship', 'uk', 'Aberdeen', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec95',
   $q$School/college leaver apprenticeship programme in Audit, Aberdeen, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Belfast - September 2027', 'apprenticeship', 'uk', 'Belfast', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec103',
   $q$School/college leaver apprenticeship programme in Audit, Belfast, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Birmingham - September 2027', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec217',
   $q$School/college leaver apprenticeship programme in Audit, Birmingham, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Bristol - September 2027', 'apprenticeship', 'uk', 'Bristol', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec177',
   $q$School/college leaver apprenticeship programme in Audit, Bristol, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Bromley - September 2027', 'apprenticeship', 'uk', 'Bromley', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec188',
   $q$School/college leaver apprenticeship programme in Audit, Bromley, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Cambridge - September 2027', 'apprenticeship', 'uk', 'Cambridge', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec180',
   $q$School/college leaver apprenticeship programme in Audit, Cambridge, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Chelmsford - September 2027', 'apprenticeship', 'uk', 'Chelmsford', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec218',
   $q$School/college leaver apprenticeship programme in Audit, Chelmsford, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Edinburgh - September 2027', 'apprenticeship', 'uk', 'Edinburgh', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec106',
   $q$School/college leaver apprenticeship programme in Audit, Edinburgh, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Gatwick - September 2027', 'apprenticeship', 'uk', 'Crawley', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec192',
   $q$School/college leaver apprenticeship programme in Audit, Crawley, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Glasgow - September 2027', 'apprenticeship', 'uk', 'Glasgow', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec110',
   $q$School/college leaver apprenticeship programme in Audit, Glasgow, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Hull - September 2027', 'apprenticeship', 'uk', 'Hull', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec115',
   $q$School/college leaver apprenticeship programme in Audit, Hull, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Leicester - September 2027', 'apprenticeship', 'uk', 'Leicester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec181',
   $q$School/college leaver apprenticeship programme in Audit, Leicester, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Liverpool - September 2027', 'apprenticeship', 'uk', 'Liverpool', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec65',
   $q$School/college leaver apprenticeship programme in Audit, Liverpool, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - London - September 2027', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec197',
   $q$School/college leaver apprenticeship programme in Audit, London, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Milton Keynes - September 2027', 'apprenticeship', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec184',
   $q$School/college leaver apprenticeship programme in Audit, Milton Keynes, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Newcastle - September 2027', 'apprenticeship', 'uk', 'Newcastle', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec120',
   $q$School/college leaver apprenticeship programme in Audit, Newcastle, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Nottingham - September 2027', 'apprenticeship', 'uk', 'Nottingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec186',
   $q$School/college leaver apprenticeship programme in Audit, Nottingham, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Preston - September 2027', 'apprenticeship', 'uk', 'Preston', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec71',
   $q$School/college leaver apprenticeship programme in Audit, Preston, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit School Leaver - Reading - September 2027', 'apprenticeship', 'uk', 'Reading', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec200',
   $q$School/college leaver apprenticeship programme in Audit, Reading, studying towards the Chartered Accountant (ACA) qualification from day one over the standard four-year route. Start date 14 Sept 2027 (fixed, mandatory). Requires min. 112 UCAS points (3 A levels) / 104 (Scottish Highers) / Irish Leaving Cert higher level; General Studies, AS levels and EPQ not accepted. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'FastTrack Audit School Leaver - Birmingham - September 2027', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec226',
   $q$Accelerated school/college leaver apprenticeship in Audit, Birmingham, completing the Chartered Accountant (ACA) qualification in three years instead of the standard four. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'FastTrack Audit School Leaver - Leeds - September 2027', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec225',
   $q$Accelerated school/college leaver apprenticeship in Audit, Leeds, completing the Chartered Accountant (ACA) qualification in three years instead of the standard four. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'FastTrack Audit School Leaver - London - September 2027', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec123',
   $q$Accelerated school/college leaver apprenticeship in Audit, London, completing the Chartered Accountant (ACA) qualification in three years instead of the standard four. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'FastTrack Audit School Leaver - Manchester - September 2027', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec224',
   $q$Accelerated school/college leaver apprenticeship in Audit, Manchester, completing the Chartered Accountant (ACA) qualification in three years instead of the standard four. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Data Analytics School Leaver - CFAB - Leeds - September 2027', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec253',
   $q$School/college leaver apprenticeship on RSM's Audit Data Analytics team, Leeds, building in-house audit tools and apps while studying towards the CFAB qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Data Analytics School Leaver - CFAB - London - September 2027', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec251',
   $q$School/college leaver apprenticeship on RSM's Audit Data Analytics team, London, building in-house audit tools and apps while studying towards the CFAB qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Data Analytics School Leaver - ACA - Leeds - September 2027', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec250',
   $q$School/college leaver apprenticeship on RSM's Audit Data Analytics team, Leeds, building in-house audit tools and apps while studying towards the ACA qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Data Analytics School Leaver - ACA - Manchester - September 2027', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec249',
   $q$School/college leaver apprenticeship on RSM's Audit Data Analytics team, Manchester, building in-house audit tools and apps while studying towards the ACA qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Audit Data Analytics School Leaver - CFAB - Manchester - September 2027', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec252',
   $q$School/college leaver apprenticeship on RSM's Audit Data Analytics team, Manchester, building in-house audit tools and apps while studying towards the CFAB qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Belfast - September 2027', 'apprenticeship', 'uk', 'Belfast', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec151',
   $q$School/college leaver apprenticeship in Consulting, Belfast, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Bristol - September 2027 - AAT', 'apprenticeship', 'uk', 'Bristol', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec154',
   $q$School/college leaver apprenticeship in Consulting, Bristol, joining the Finance Function Support or Risk and Governance team studying towards the AAT qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Bristol - September 2027 - CMDA', 'apprenticeship', 'uk', 'Bristol', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec155',
   $q$School/college leaver apprenticeship in Consulting, Bristol, joining the Finance Function Support or Risk and Governance team studying towards the CMDA qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Chelmsford - September 2027 - CMD', 'apprenticeship', 'uk', 'Chelmsford', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec159',
   $q$School/college leaver apprenticeship in Consulting, Chelmsford, joining the Finance Function Support or Risk and Governance team studying towards the CMD qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Gatwick - April 2027 - AAT', 'apprenticeship', 'uk', 'Crawley', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec290',
   $q$School/college leaver apprenticeship in Consulting, Crawley, joining the Finance Function Support or Risk and Governance team studying towards the AAT qualification. Start date April 2027. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Glasgow - September 2027', 'apprenticeship', 'uk', 'Glasgow', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec160',
   $q$School/college leaver apprenticeship in Consulting, Glasgow, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Guildford - April 2027 - AAT', 'apprenticeship', 'uk', 'Guildford', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec289',
   $q$School/college leaver apprenticeship in Consulting, Guildford, joining the Finance Function Support or Risk and Governance team studying towards the AAT qualification. Start date April 2027. Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Leeds - September 2027 - AAT', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec162',
   $q$School/college leaver apprenticeship in Consulting, Leeds, joining the Finance Function Support or Risk and Governance team studying towards the AAT qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Liverpool - September 2027', 'apprenticeship', 'uk', 'Liverpool', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec165',
   $q$School/college leaver apprenticeship in Consulting, Liverpool, joining the Finance Function Support or Risk and Governance team. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Manchester - September 2027 - AAT', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec168',
   $q$School/college leaver apprenticeship in Consulting, Manchester, joining the Finance Function Support or Risk and Governance team studying towards the AAT qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Manchester - September 2027 - CMDA', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec142',
   $q$School/college leaver apprenticeship in Consulting, Manchester, joining the Finance Function Support or Risk and Governance team studying towards the CMDA qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Preston - September 2027 - CMDA', 'apprenticeship', 'uk', 'Preston', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec172',
   $q$School/college leaver apprenticeship in Consulting, Preston, joining the Finance Function Support or Risk and Governance team studying towards the CMDA qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Leicester - September 2027 - AAT', 'apprenticeship', 'uk', 'Leicester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec164',
   $q$School/college leaver apprenticeship in Consulting, Leicester, joining the Finance Function Support or Risk and Governance team studying towards the AAT qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Consulting School Leaver - Milton Keynes - September 2027 - CMDA', 'apprenticeship', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec146',
   $q$School/college leaver apprenticeship in Consulting, Milton Keynes, joining the Finance Function Support or Risk and Governance team studying towards the CMDA qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Birmingham - September 2027', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec93',
   $q$School/college leaver apprenticeship in Tax, Birmingham, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Glasgow - September 2027', 'apprenticeship', 'uk', 'Glasgow', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec88',
   $q$School/college leaver apprenticeship in Tax, Glasgow, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Guildford - September 2027', 'apprenticeship', 'uk', 'Guildford', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec91',
   $q$School/college leaver apprenticeship in Tax, Guildford, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Leeds - September 2027', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec109',
   $q$School/college leaver apprenticeship in Tax, Leeds, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Leicester - September 2027', 'apprenticeship', 'uk', 'Leicester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec128',
   $q$School/college leaver apprenticeship in Tax, Leicester, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Liverpool - September 2027', 'apprenticeship', 'uk', 'Liverpool', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec131',
   $q$School/college leaver apprenticeship in Tax, Liverpool, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - London - September 2027', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec139',
   $q$School/college leaver apprenticeship in Tax, London, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Manchester - September 2027', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec143',
   $q$School/college leaver apprenticeship in Tax, Manchester, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true),
  ('RSM UK', 'Tax School Leaver - Stoke - September 2027', 'apprenticeship', 'uk', 'Stoke On Trent', 'United Kingdom', 2027, 'open',
   null, 'https://www.rsmuk.com/careers/jobs/ec97',
   $q$School/college leaver apprenticeship in Tax, Stoke On Trent, working across specialisms such as VAT/indirect tax, employer solutions, private client, corporate tax, transfer pricing and tax investigations (availability varies by office) while studying towards a professional tax qualification. Start date 14 Sept 2027 (fixed, mandatory). Sourced 28 Sept 2026.$q$,
   'unknown', '2026-09-28', true);
