-- Opportunities added 6 Oct 2026 (part 2).
-- Founder spotted these roles on LinkedIn and asked for them to be added.
-- LinkedIn is not an acceptable source, so each role was found and verified
-- on the employer's own careers site/ATS and checked against existing rows
-- first. Where the employer's page title differed from LinkedIn's, the
-- employer's title is used. Roles that could not be verified on an employer
-- site, were no longer live, or required prior experience were left out.
-- Already applied directly to production via the Supabase admin client -
-- this file is kept for the repo's audit trail.

insert into public.opportunities
  (company, role_title, category, region, city, country, cycle_year, status,
   deadline, apply_url, notes, visa_sponsorship, is_published)
values
  ('KPMG', 'Audit Apprenticeship - Autumn 2027', 'apprenticeship', 'other', 'Gibraltar', 'Gibraltar', 2027, 'rolling',
   null, 'https://www.kpmgcareers.co.uk/Vacancies/ApprenticeshipsAuditApprenticeshipGibraltarAutumn2027/a71a458d-66a4-0283-b52f-32fef2893b7d',
   $q$Listed on KPMG UK careers site as Audit Apprenticeship Gibraltar Autumn 2027 (site title: Apprenticeships Audit - Apprenticeship Gibraltar Autumn 2027). 5-year programme working towards AAT Level 3/4 plus ACA; Gibraltar is a British Overseas Territory so not strictly UK. No deadline stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Hymans Robertson', 'Pensions Governance & Investment Consulting: Graduate Programme', 'grad_scheme', 'uk', 'Birmingham, Edinburgh, Glasgow, London', 'United Kingdom', 2027, 'open',
   '2026-10-09', 'https://hymans.current-vacancies.com/Jobs/Advert/4335911?cid=2054&t=Pensions-Governance-And-Investment-Consulting--Graduate-Programme',
   $q$CLOSING SOON: posting closes 9 Oct 2026 23:59 BST (recruiting on a rolling basis so may fill earlier). Permanent graduate role aligned to the Investment DB or DC Consulting team, salary GBP 32,500-34,500 by location, with IFoA or CFA study support. Posting says it does not currently meet the Skilled Worker salary threshold for sponsorship. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Hymans Robertson', 'Actuarial Consulting & Analytics: Graduate Programme', 'grad_scheme', 'uk', 'Birmingham, Edinburgh, Glasgow, London', 'United Kingdom', 2027, 'open',
   '2026-11-05', 'https://hymans.current-vacancies.com/Jobs/Advert/4335802?cid=2054&t=Actuarial-Consulting-And-Analytics--Graduate-Programme',
   $q$Permanent graduate programme joining Actuarial Private, Actuarial Public or the Insights & Analytics team, salary GBP 32,500-34,500 by location. Posting closes 5 Nov 2026 and says it does not currently meet the Skilled Worker salary threshold for sponsorship. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Hymans Robertson', 'Pensions Governance & Investment Consulting: Summer Internship Programme', 'summer_internship', 'uk', 'Birmingham, Edinburgh, Glasgow, London', 'United Kingdom', 2027, 'open',
   '2026-11-08', 'https://hymans.current-vacancies.com/Jobs/Advert/4335935?cid=2054&t=Pensions-Governance-And-Investment-Consulting--Summer-Internship-Programme',
   $q$Eight-week paid internship over July and August 2027, open to penultimate-year students only, salary GBP 24,500-27,000 by location. Strong performers may get a ring-fenced graduate place; posting closes 8 Nov 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Hymans Robertson', 'Actuarial Consulting & Analytics: Summer Internship Programme', 'summer_internship', 'uk', 'Birmingham, Edinburgh, Glasgow, London', 'United Kingdom', 2027, 'open',
   '2026-11-08', 'https://hymans.current-vacancies.com/Jobs/Advert/4335929?cid=2054&t=Actuarial-Consulting-And-Analytics--Summer-Internship-Programme',
   $q$Eight-week paid internship over July and August 2027, open to penultimate-year students only, salary GBP 24,500-27,000 by location. Strong performers may get a ring-fenced graduate place; posting closes 8 Nov 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Baringa', 'Graduate Analyst Programme - Financial Services', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-19', 'https://job-boards.eu.greenhouse.io/baringa/jobs/4994434101',
   $q$CLOSING SOON: applications close Monday 19 Oct 2026 12pm GMT; assessment centres in New Year 2027, start September 2027. Permanent analyst role; requires permanent right to work in the UK and Baringa states it cannot sponsor. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Baringa', 'Graduate Analyst Programme - Capabilities', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-19', 'https://job-boards.eu.greenhouse.io/baringa/jobs/4994128101',
   $q$CLOSING SOON: applications close Monday 19 Oct 2026 12pm GMT; assessment centres in New Year 2027, start September 2027. Permanent analyst role; requires permanent right to work in the UK and Baringa states it cannot sponsor. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Baringa', 'Graduate Analyst Programme - Energy & Resources', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-19', 'https://job-boards.eu.greenhouse.io/baringa/jobs/4990860101',
   $q$CLOSING SOON: applications close Monday 19 Oct 2026 12pm GMT; assessment centres in New Year 2027, start September 2027. Permanent analyst role; requires permanent right to work in the UK and Baringa states it cannot sponsor. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Baringa', 'Graduate Analyst Programme - Products & Services', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-19', 'https://job-boards.eu.greenhouse.io/baringa/jobs/4994036101',
   $q$CLOSING SOON: applications close Monday 19 Oct 2026 12pm GMT; assessment centres in New Year 2027, start September 2027. Permanent analyst role; requires permanent right to work in the UK and Baringa states it cannot sponsor. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Baringa', 'Graduate Analyst Programme - Public Sector Consulting', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-19', 'https://job-boards.eu.greenhouse.io/baringa/jobs/4994406101',
   $q$CLOSING SOON: applications close Monday 19 Oct 2026 12pm GMT; assessment centres in New Year 2027, start May and September 2027; must be eligible for UK Security Check (SC) clearance. Permanent analyst role; requires permanent right to work in the UK and Baringa states it cannot sponsor. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('CGI', 'Business Graduate - Commercial, Growth and Business Development - 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2614&BRID=1338409&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2614), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Business Graduate - Business Analysis & Consulting 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2613&BRID=1338643&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2613), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Business Graduate - Project Delivery - 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2599&BRID=1338411&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2599), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Business Graduate - Project Manager - January 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2634&BRID=1338407&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2634), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Graduate - Technology Engineer - Software, Cloud & Infrastructure 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0240&BRID=1338400&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0240), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Graduate - Applied AI Engineering & Deployment 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0265&BRID=1338394&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0265), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Graduate - January 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2291&BRID=1338417&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2291), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Graduate - Data Analysis & Data Science 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0214&BRID=1338405&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0214), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Graduate - Cyber Security 2027', 'grad_scheme', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0229&BRID=1338403&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0229), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'User Experience Graduate - 2027', 'grad_scheme', 'uk', 'Various', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0234&BRID=1338401&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0234), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Graduate - Cloud Engineer - Belfast - January 2027 start date', 'grad_scheme', 'uk', 'Belfast', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0269&BRID=1338392&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0269), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Industrial Placement 2027', 'placement_year', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2321&BRID=1338415&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2321), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Business Industrial Placement 2027', 'placement_year', 'uk', 'UK Wide', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0926-2490&BRID=1338413&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J0926-2490), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('CGI', 'Technical Industrial Placement - Northern Ireland 2027', 'placement_year', 'uk', 'Belfast', 'United Kingdom', 2027, 'rolling',
   null, 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J1026-0556&BRID=1339139&lang=1',
   $q$CGI early-career role listed on CGI's UK careers site (position J1026-0556), location UK-wide. Check the posting for the start date and closing date. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Corporate Experience', 'grad_scheme', 'uk', 'London, Glasgow, Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Corporate-Experience/1443137833/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; posting lists London, Glasgow and Manchester but start months shown only for London (February and June 2027), so check Glasgow availability. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Workforce and Organisation', 'grad_scheme', 'uk', 'London, Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Workforce-and-Organisation/1443143833/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months February (London), April (London and Manchester), June (London). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - FROG', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-FROG/1443124533/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months February, April and June. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Business Technology', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Business-Technology/1443126833/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months February, April and June. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Enterprise Data & Analytics', 'grad_scheme', 'uk', 'London, Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Enterprise-Data-&-Analytics/1443135933/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months February (London), April (Glasgow), June (London). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Public Sector', 'grad_scheme', 'uk', 'London, Manchester, Newcastle upon Tyne, Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Public-Sector/1443175033/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months February (London), April (Manchester and Glasgow), June (London). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Financial Services', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Financial-Services/1443144933/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months not listed on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Intelligent Industries', 'grad_scheme', 'uk', 'London, Manchester, Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Intelligent-Industries/1443141333/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months February (London), April (Manchester and Glasgow), June (London). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini Invent', 'Accelerate Graduate Programme - Energy & Utilities', 'grad_scheme', 'uk', 'London, Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Accelerate-Graduate-Programme-Energy-&-Utilities/1443146133/',
   $q$Capgemini Invent Associate Consultant graduate programme (about 19-21 months to Consultant); minimum 2:2 degree and security-clearance eligibility checks apply. Posted 1 Oct 2026 with no deadline stated; start months not listed on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate Software Developer 2027', 'grad_scheme', 'uk', 'London, Birmingham, Bristol, Manchester, Cardiff, Inverness, Woking', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Graduate-Software-Developer-2027/1444710733/',
   $q$Graduate programme with April intake, salary GBP 35,000; minimum 2:2 degree. Posted 6 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate Business Analyst 2027', 'grad_scheme', 'uk', 'London, Birmingham, Bristol, Manchester, Cardiff, Inverness, Woking', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Graduate-Business-Analyst-2027/1444701333/',
   $q$Graduate programme with April intake, salary GBP 35,000; minimum 2:2 degree. Posted 6 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate Project Manager 2027', 'grad_scheme', 'uk', 'London, Birmingham, Glasgow, Manchester, Cardiff, Woking', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Graduate-Project-Manager-2027/1443167833/',
   $q$Graduate programme with April 2027 intake, salary GBP 35,000; minimum 2:2 degree. Posted 1 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate DevOps Engineer in Test - Quality Engineering (Consultant) 2027', 'grad_scheme', 'uk', 'London, Birmingham, Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/London-Graduate-DevOps-Engineer-in-Test-Quality-Engineering-%28Consultant%29-2027/1442952433/',
   $q$Graduate programme with April intake, salary GBP 35,000; minimum 2:2 degree. Sogeti brand within Capgemini; posted 30 Sept 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate Software Engineering Programme 2027', 'grad_scheme', 'uk', 'Telford, Hove', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/Telford-Graduate-Software-Engineering-Programme-2027/1443168333/',
   $q$Graduate programme, salary GBP 35,000; minimum 2:2 degree. Posted 1 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate Customer Experience (CX) Analyst Programme', 'grad_scheme', 'uk', 'Telford, Hove', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/Telford-Graduate-Customer-Experience-%28CX%29-Analyst-Programme/1443169233/',
   $q$Graduate programme with April 2027 intake, salary GBP 35,000; minimum 2:2 degree. Posted 1 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Project Management & Operations Analyst Graduate 2027', 'grad_scheme', 'uk', 'Telford', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/Telford-Project-Management-&-Operations-Analyst-Graduate-2027/1443163133/',
   $q$Graduate programme, salary GBP 35,000; minimum 2:2 degree. Posted 1 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Graduate UX Programme 2027', 'grad_scheme', 'uk', 'Hove', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/Hove-Graduate-UX-Programme-2027/1443181733/',
   $q$Graduate programme, salary GBP 35,000; minimum 2:2 degree. Posted 1 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'SAP Graduate Technology Consultant Programme 2027', 'grad_scheme', 'uk', 'Hove', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/Hove-SAP-Graduate-Technology-Consultant-Programme-2027/1443169833/',
   $q$Graduate programme, salary GBP 35,000; minimum 2:2 degree. Posted 1 Oct 2026. No deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Capgemini', 'Internship Consulting or Technical Routes 2027', 'summer_internship', 'uk', 'Telford', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.capgemini.com/job/Telford-Internship-Consulting-or-Technical-Routes-2027/1443185333/',
   $q$Eight-week internship starting June 2027 supporting a UK public sector client, salary GBP 26,230 pro rata. Posted 1 Oct 2026 with no deadline stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax Graduate Programme (Autumn 2027) - Birmingham', 'grad_scheme', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-graduate-programme-autumn-2027---birmingham_trn27_1962/',
   $q$Tax graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Glasgow', 'grad_scheme', 'uk', 'Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---glasgow_trn27_1302/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Edinburgh', 'grad_scheme', 'uk', 'Edinburgh', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---edinburgh_trn27_1252/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Edinburgh', 'grad_scheme', 'uk', 'Edinburgh', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---edinburgh_trn27_1232/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Cardiff', 'grad_scheme', 'uk', 'Cardiff', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---cardiff_trn27_1172/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Bristol', 'grad_scheme', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---bristol_trn27_1122/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Bristol', 'grad_scheme', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---bristol_trn27_1102/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Grants Audit Graduate Programme (Autumn 2027) - Birmingham', 'grad_scheme', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/grants-audit-graduate-programme-autumn-2027---birmingham_trn27_1092/',
   $q$Grants Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Birmingham', 'grad_scheme', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---birmingham_trn27_1072/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Not For Profit Graduate Programme (Autumn 2027) - Birmingham', 'grad_scheme', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/not-for-profit-graduate-programme--autumn-2027---birmingham_trn27_1052/',
   $q$Not For Profit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Transaction Advisory Services Graduate Programme (Autumn 2027) - Regions (Birmingham, Leeds & Manchester)', 'grad_scheme', 'uk', 'Birmingham, Leeds & Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/transaction-advisory-services-graduate-programme--autumn-2027---regions-birmingham-leeds--manchester_trn27_188/',
   $q$Transaction Advisory Services graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Transaction Advisory Services Graduate Programme (Autumn 2027) - Regions (Cambridge & Milton Keynes)', 'grad_scheme', 'uk', 'Cambridge & Milton Keynes', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/transaction-advisory-services-graduate-programme--autumn-2027---regions-cambridge--milton-keynes_trn27_1872/',
   $q$Transaction Advisory Services graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Southampton', 'apprenticeship', 'uk', 'Southampton', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---southampton_trn27_1832/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Southampton', 'grad_scheme', 'uk', 'Southampton', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---southampton_trn27_1822/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Sheffield', 'apprenticeship', 'uk', 'Sheffield', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---sheffield_trn27_1812/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Reading', 'apprenticeship', 'uk', 'Reading', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---reading_trn27_1782/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Reading', 'grad_scheme', 'uk', 'Reading', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---reading_trn27_1772/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Oxford', 'apprenticeship', 'uk', 'Oxford', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---oxford_trn27_1762/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax School Leaver Programme (Autumn 2027) - Manchester', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-school-leaver-programme-autumn-2027----manchester_trn27_200/',
   $q$Tax school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax School Leaver Programme (Autumn 2027) - Birmingham', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-school-leaver-programme-autumn-2027---birmingham_trn27_199/',
   $q$Tax school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax School Leaver Programme (Autumn 2027) - London', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-school-leaver-programme-autumn-2027---london_trn27_198/',
   $q$Tax school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-graduate-programme-autumn-2027---london_trn27_195/',
   $q$Tax graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Oxford', 'grad_scheme', 'uk', 'Oxford', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---oxford_trn27_1752/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Milton Keynes', 'apprenticeship', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---milton-keynes_trn27_1742/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Milton Keynes', 'grad_scheme', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---milton-keynes_trn27_1732/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Accounting Services Graduate Programme (Autumn 2027) - Milton Keynes', 'grad_scheme', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/accounting-services-graduate-programme-autumn-2027---milton-keynes_trn27_1722/',
   $q$Accounting Services graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - Manchester', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---manchester_trn27_1692/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Manchester', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---manchester_trn27_1672/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Pension Audit School Leaver Programme (Autumn 2027) - Manchester', 'apprenticeship', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/pension-audit-school-leaver-programme-autumn-2027---manchester_trn27_1652/',
   $q$Pension Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Not for Profit Audit School Leaver Programme (Autumn 2027 ) - London', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/not-for-profit-audit-school-leaver-programme-autumn-2027----london_trn27_1622/',
   $q$Not for Profit Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Not For Profit Audit Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/not-for-profit-audit-graduate-programme-autumn-2027---london_trn27_1612/',
   $q$Not For Profit Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - London', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---london_trn27_156/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---london_trn27_1552/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - London', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---london_trn27_1542/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---london_trn27_1532/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'IT Audit School Leaver Programme (Autumn 2027) - London', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/it-audit-school-leaver-programme-autumn-2027---london_trn27_152/',
   $q$IT Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'IT Audit Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/it-audit-graduate-programme-autumn-2027---london_trn27_1512/',
   $q$IT Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Financial Services Audit School Leaver Programme (Autumn 2027) - London', 'apprenticeship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/financial-services-audit-school-leaver-programme-autumn-2027---london_trn27_1502/',
   $q$Financial Services Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Financial Services Audit Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/financial-services-audit-graduate-programme-autumn-2027---london_trn27_1492/',
   $q$Financial Services Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - Liverpool', 'apprenticeship', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---liverpool_trn27_1482/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Liverpool', 'apprenticeship', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---liverpool_trn27_1462/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Leicester', 'apprenticeship', 'uk', 'Leicester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---leicester_trn27_1432/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - Leeds', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---leeds_trn27_1372/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Leeds', 'apprenticeship', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---leeds_trn27_1352/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - Glasgow', 'apprenticeship', 'uk', 'Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---glasgow_trn27_1332/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Glasgow', 'apprenticeship', 'uk', 'Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---glasgow_trn27_1312/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Gatwick', 'apprenticeship', 'uk', 'Gatwick', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme--autumn-2027---gatwick_trn27_128/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Gatwick', 'grad_scheme', 'uk', 'Gatwick', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme--autumn-2027---gatwick_trn27_127/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Edinburgh', 'apprenticeship', 'uk', 'Edinburgh', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---edinburgh_trn27_124/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Colchester', 'apprenticeship', 'uk', 'Colchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---colchester_trn27_122/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Colchester', 'grad_scheme', 'uk', 'Colchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---colchester_trn27_121/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Cardiff', 'apprenticeship', 'uk', 'Cardiff', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---cardiff_trn27_118/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,150. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Cambridge', 'apprenticeship', 'uk', 'Cambridge', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---cambridge_trn27_115/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - Bristol', 'apprenticeship', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---bristol_trn27_113/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,150. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Bristol', 'apprenticeship', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---bristol_trn27_111/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,150. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit School Leaver Programme (Autumn 2027) - Birmingham', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-school-leaver-programme-autumn-2027---birmingham_trn27_108/',
   $q$Public Sector Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Not For Profit School Leaver Programme (Autumn 2027) - Birmingham', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/not-for-profit-school-leaver-programme-autumn-2027---birmingham_trn27_106/',
   $q$Not For Profit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Cambridge', 'grad_scheme', 'uk', 'Cambridge', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---cambridge_trn27_-114/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Corporate Finance Advisory Graduate Programme (Autumn 2027) - Regions (Birmingham, Leeds & Manchester)', 'grad_scheme', 'uk', 'Birmingham, Leeds & Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/corporate-finance-advisory-graduate-programme-autumn-2027---regions-birmingham-leeds--manchester_trn27_230/',
   $q$Corporate Finance Advisory graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - Glasgow', 'placement_year', 'uk', 'Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---glasgow_trn27_2282/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - Manchester', 'placement_year', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---manchester_trn27_2272/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - Leeds', 'placement_year', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---leeds_trn27_2262/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - Liverpool', 'placement_year', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---liverpool_trn27_2252/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - Bristol', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---bristol_trn27_224/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,150. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - Birmingham', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---birmingham_trn27_223/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit 12 Month Placement Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-12-month-placement-programme-summer-2027---london_trn27_222/',
   $q$Public Sector Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Southampton', 'placement_year', 'uk', 'Southampton', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---southampton_trn27_2212/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Reading', 'placement_year', 'uk', 'Reading', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---reading_trn27_2202/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Oxford', 'placement_year', 'uk', 'Oxford', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---oxford_trn27_2192/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Milton Keynes', 'placement_year', 'uk', 'Milton Keynes', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---milton-keynes_trn27_2182/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Manchester', 'placement_year', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---manchester_trn27_2172/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'IT Audit 12 Month Placement Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/it-audit-12-month-placement-programme-summer-2027---london_trn27_2162/',
   $q$IT Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---london_trn27_2152/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Financial Services Audit 12 Month Placement Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/financial-services-audit-12-month-placement-programme-summer-2027---london_trn27_2142/',
   $q$Financial Services Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Liverpool', 'placement_year', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---liverpool_trn27_2132/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Leicester', 'placement_year', 'uk', 'Leicester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---leicester_trn27_2122/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Leeds', 'placement_year', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---leeds_trn27_2112/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Gatwick', 'placement_year', 'uk', 'Gatwick', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---gatwick_trn27_2102/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Colchester', 'placement_year', 'uk', 'Colchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---colchester_trn27_2092/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Cardiff', 'placement_year', 'uk', 'Cardiff', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---cardiff_trn27_2082/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,150. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Cambridge', 'placement_year', 'uk', 'Cambridge', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---cambridge_trn27_2072/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,300. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Bristol', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---bristol_trn27_2062/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,150. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Not For Profit Audit 12 Month Placement Programme (Summer 2027) - Birmingham', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/not-for-profit-audit-12-month-placement-programme-summer-2027---birmingham_trn27_2052/',
   $q$Not For Profit Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit 12 Month Placement Programme (Summer 2027) - Birmingham', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-12-month-placement-programme-summer-2027---birmingham_trn27_2042/',
   $q$Private Capital Audit 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax 12 Month Placement Programme (Summer 2027) - Manchester', 'placement_year', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-12-month-placement-programme-summer-2027---manchester_trn27_2032/',
   $q$Tax 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax 12 Month Placement Programme (Summer 2027) - Birmingham', 'placement_year', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-12-month-placement-programme--summer-2027---birmingham_trn27_2022/',
   $q$Tax 12-month fixed-term placement starting Summer 2027; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax 12 Month Placement Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-12-month-placement-programme-summer-2027---london_trn27_2012/',
   $q$Tax 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Corporate Finance Advisory Graduate Programme (Autumn 2027) - Regions (Milton Keynes & Cambridge)', 'grad_scheme', 'uk', 'Milton Keynes & Cambridge', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/corporate-finance-advisory-graduate-programme-autumn-2027---regions-milton-keynes--cambridge_trn27_194/',
   $q$Corporate Finance Advisory graduate programme, permanent role starting Autumn 2027; stated salary GBP 37,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Corporate Finance Advisory Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/corporate-finance-advisory-graduate-programme-autumn-2027---london_trn27_193/',
   $q$Corporate Finance Advisory graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Insolvency and Asset Recovery 12 month Placement Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/insolvency-and-asset-recovery-12-month-placement-programme-summer-2027----london_trn27_192/',
   $q$Insolvency and Asset Recovery 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Insolvency and Asset Recovery Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/insolvency-and-asset-recovery-graduate-programme-autumn-2027---london_trn27_191/',
   $q$Insolvency and Asset Recovery graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Debt Capital Advisory Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/debt-capital-advisory-graduate-programme-autumn-2027---london_trn27_190/',
   $q$Debt Capital Advisory graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Forensics Advisory Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/forensics-advisory-graduate-programme-autumn-2027---london_trn27_189/',
   $q$Forensics Advisory graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Transaction Advisory Services Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/transaction-advisory-services-graduate-programme--autumn-2027---london_trn27_186/',
   $q$Transaction Advisory Services graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Turnaround & Restructuring 12 Month Programme (Summer 2027) - London', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/turnaround--restructuring-12-month-programme-summer-2027---london_trn27_185/',
   $q$Turnaround & Restructuring 12-month fixed-term placement starting Summer 2027; stated salary GBP 31,750. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Turnaround & Restructuring Graduate Programme (Autumn 2027) - London', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/turnaround--restructuring-graduate-programme-autumn-2027---london_trn27_184/',
   $q$Turnaround & Restructuring graduate programme, permanent role starting Autumn 2027; stated salary GBP 40,000 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit School Leaver Programme (Autumn 2027) - Birmingham', 'apprenticeship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-school-leaver-programme-autumn-2027---birmingham_trn27_1022/',
   $q$Private Capital Audit school leaver programme, permanent role starting Autumn 2027 combining work with a professional qualification; stated salary GBP 29,000. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Birmingham', 'grad_scheme', 'uk', 'Birmingham', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---birmingham_trn27_1012/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Tax Graduate Programme (Autumn 2027) - Manchester', 'grad_scheme', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/tax-graduate-programme-autumn-2027---manchester_trn27_197/',
   $q$Tax graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Sheffield', 'grad_scheme', 'uk', 'Sheffield', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---sheffield_trn27_180/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Accounting Services Graduate Programme (Autumn 2027) - Sheffield', 'grad_scheme', 'uk', 'Sheffield', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/accounting-services-graduate-programme-autumn-2027---sheffield_trn27_179/',
   $q$Accounting Services graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Manchester', 'grad_scheme', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---manchester_trn27_168/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Manchester', 'grad_scheme', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---manchester_trn27_166/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Pension Audit Graduate Programme (Autumn 2027) - Manchester', 'grad_scheme', 'uk', 'Manchester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/pension-audit-graduate-programme-autumn-2027---manchester_trn27_164/',
   $q$Pension Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Liverpool', 'grad_scheme', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---liverpool_trn27_147/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Liverpool', 'grad_scheme', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---liverpool_trn27_145/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Accounting Services Graduate Programme (Autumn 2027) - Liverpool', 'grad_scheme', 'uk', 'Liverpool', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/accounting-services-graduate-programme-autumn-2027---liverpool_trn27_144/',
   $q$Accounting Services graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Leicester', 'grad_scheme', 'uk', 'Leicester', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---leicester_trn27_142/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Value For Money Graduate Programme (Autumn 2027) - Leeds', 'grad_scheme', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/value-for-money-graduate-programme-autumn-2027---leeds_trn27_140/',
   $q$Value For Money graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Leeds', 'grad_scheme', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---leeds_trn27_136/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Private Capital Audit Graduate Programme (Autumn 2027) - Leeds', 'grad_scheme', 'uk', 'Leeds', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/private-capital-audit-graduate-programme-autumn-2027---leeds_trn27_134/',
   $q$Private Capital Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Grant Thornton', 'Public Sector Audit Graduate Programme (Autumn 2027) - Glasgow', 'grad_scheme', 'uk', 'Glasgow', 'United Kingdom', 2027, 'rolling',
   null, 'https://www.grantthornton.co.uk/careers/early-careers-job-search/public-sector-audit-graduate-programme-autumn-2027---glasgow_trn27_132/',
   $q$Public Sector Audit graduate programme, permanent role starting Autumn 2027; stated salary GBP 34,250 with a fully funded professional qualification. No application deadline stated on the posting. Sourced 6 Oct 2026.$q$,
   'unknown', true);

-- KPMG vacancies that now return an HTTP 500 (removed) on kpmgcareers.co.uk
-- while comparable live KPMG vacancies return 200 - marked closed.
update public.opportunities set status = 'closed'
where id in (
  '06dd48fa-a59d-4fb6-9322-88aabb174b32', -- Audit Vacation Programme - July 2027, Manchester
  '2797d745-e116-4e3b-bc4c-a476676795a2', -- Graduate Audit - Accounting Advisory and Assurance, Manchester
  '1a5e6b12-1c78-40bd-a96e-945591adfeb7', -- Graduate Audit - Technology Audit, London
  'd2fd1bb2-4555-4203-9f1f-9cbdc2db6832', -- Graduate Technology - Technology Consulting in Tax, Glasgow
  '5da5a701-4ab2-4d9f-8974-816640eb3e91', -- Tax Apprenticeship, Birmingham
  '84a5d135-1d1b-4fe8-bb69-367485afe5f8', -- Tax Apprenticeship, London
  '16960d28-2e8c-4290-b4a5-bfabed7190c9', -- Tax Vacation Programme, Manchester
  '889cc04c-ef3c-47d5-86a1-e945dd4b4c75'  -- Tax Vacation Programme, London
);

-- Student-facing note clean-up for rows added in part 1.
update public.opportunities
set notes = 'Graduate consultant in the Asset Management Transformation team, salary 31,000 GBP, hybrid working offered, minimum 2:1 degree (preferably STEM). Amey may close the vacancy early, so apply soon. Sourced 6 Oct 2026.'
where company = 'Amey' and role_title = 'Graduate Asset Management Consultant';
