-- New opportunities added 28 Sept 2026.
-- Founder asked to check the 8 companies from the carousel-deck project for
-- new roles. Oliver Wyman had only 2 rows tracked - very thin coverage.
-- Found 25 new UK/EU/Switzerland postings: full-time entry-level consultant
-- graduate schemes (London, Paris, Brussels, Madrid x2, Stockholm,
-- Copenhagen, Zurich), internships (Newcastle x2, Amsterdam x3, Berlin x2,
-- Madrid x2, Copenhagen x2, Stockholm, Milan, Warsaw, Paris), a Bath
-- University placement, and a Data & Analytics research fellowship.
-- Verified directly on Oliver Wyman's real ATS (careers.marsh.com - Oliver
-- Wyman is part of Marsh McLennan and shares its Phenom-based careers
-- platform), reached via oliverwyman.com/careers's "Apply Now" link - not
-- aggregator data. Static fetches of this ATS unreliably show a false
-- "filled" placeholder; all postings here were verified via a JS-rendered
-- browser session.
-- Already applied directly to production via the Supabase admin client -
-- this file is kept for the repo's audit trail.

insert into public.opportunities
  (company, role_title, category, region, city, country, cycle_year, status,
   deadline, apply_url, notes, visa_sponsorship, is_published)
values
  ('Oliver Wyman', 'Entry Level Consultant - London', 'entry_level', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_324645/Oliver-Wyman-Entry-Level-Consultant-London',
   $q$Generalist (non-actuarial) full-time graduate entry-level consulting role in London, distinct from the existing Actuarial entry-level track. Requires a Bachelor's degree, native/fluent English, and openness to UK and international travel. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Bath University Placement - 2027', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_363394/Oliver-Wyman-Bath-University-Placement-2027',
   $q$Placement year specifically for University of Bath BSc Business students in their penultimate year. Involves 2-3 consulting projects with real client exposure, mentorship and professional development. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Data & Analytics Research Fellowship - Newcastle upon Tyne', 'other', 'uk', 'Newcastle upon Tyne', 'United Kingdom', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_327852/Oliver-Wyman-Data-Analytics-Research-Fellowship-Newcastle-upon-Tyne',
   $q$Fellowship for PhD students/early-career researchers in quantitative disciplines, applying data science, advanced analytics and AI to client problems. Requires Python/R proficiency. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Data & Analytics Summer Internship 2027 - Newcastle', 'summer_internship', 'uk', 'Newcastle upon Tyne', 'United Kingdom', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_364984/Oliver-Wyman-Data-Analytics-Summer-Internship-2027-Newcastle',
   $q$10-week summer internship for penultimate-year STEM/quantitative students, working on real projects (NLP tools, portfolio decarbonisation modelling, promo optimisation). Requires Python/R, UK work eligibility. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Recruiting Intern (30-40 hrs/wk, up to 12 months) - Amsterdam', 'internship', 'eu', 'Amsterdam', 'Netherlands', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_348026/Oliver-Wyman-Recruiting-Intern-30-40-hours-per-week-up-to-12-months-Amsterdam',
   $q$Entry-level HR/talent-acquisition internship supporting the full Dutch recruiting lifecycle. Requires English + Dutch, Master's student/in-progress. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Data & Analytics Consulting Intern - Berlin', 'internship', 'eu', 'Berlin', 'Germany', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_326124/Oliver-Wyman-Data-Analytics-Consulting-Intern-m-f-d-Berlin',
   $q$D&A internship in Berlin for quantitative-discipline students. Requires German + English, Python/R. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Data & Analytics Consulting Intern - Berlin (Financial Services/Energy/Retail)', 'internship', 'eu', 'Berlin', 'Germany', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_366549/Oliver-Wyman-Data-Analytics-Consulting-Intern-m-f-d-Berlin',
   $q$Separate D&A internship posting in Berlin, financial services/energy/retail/sustainability focus. Requires German + English, Python/R, willingness to travel/on-site. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Intern Consultant - Spanish speaker - Madrid', 'internship', 'eu', 'Madrid', 'Spain', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_363927/2027-Oliver-Wyman-Intern-Consultant-Spanish-speaker-m-f-d-Madrid',
   $q$Consulting internship fully integrated into project teams, for students graduating within 1-2 years. Requires fluent Spanish + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Intern Consultant - Portuguese speaker - Madrid', 'internship', 'eu', 'Madrid', 'Spain', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_363928/2027-Oliver-Wyman-Intern-Consultant-Portuguese-speaker-m-f-d-Madrid',
   $q$Consulting internship fully integrated into project teams, for students graduating within 1-2 years. Requires fluent Portuguese + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Consultant Intern 2027 - Copenhagen', 'internship', 'eu', 'Copenhagen', 'Denmark', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_362878/Oliver-Wyman-Consultant-Intern-m-f-d-2027-Copenhagen',
   $q$8-12 week consulting internship. Requires Danish + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Consultant Student Worker 2027 - Copenhagen', 'other', 'eu', 'Copenhagen', 'Denmark', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_365765/Oliver-Wyman-Consultant-Student-Worker-m-f-d-2027-Copenhagen',
   $q$Part-time (15-25 hrs/wk) ongoing student-worker consulting role supporting proposals and live projects. Requires Danish/Nordic language + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Data & Analytics Intern Analyst - Amsterdam', 'internship', 'eu', 'Amsterdam', 'Netherlands', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_364450/Oliver-Wyman-Data-Analytics-Intern-Analyst-Amsterdam',
   $q$D&A internship building analytics tools (decarbonisation modelling, GenAI chatbot validation). Requires Master's in quantitative field, Python/R, English (Dutch a plus). Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Part-time Recruitment Intern (4-6 month contract) - Warsaw', 'internship', 'eu', 'Warsaw', 'Poland', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_364602/Oliver-Wyman-Part-time-Recruitment-Intern-4-6-month-contract-Warsaw',
   $q$Part-time (20-25 hrs/wk) recruiting-coordination internship. Requires fluent English, current student/recent grad. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Consultant Intern 2027 - Stockholm', 'internship', 'eu', 'Stockholm', 'Sweden', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_361710/Oliver-Wyman-Consultant-Intern-m-f-d-2027-Stockholm',
   $q$8-12 week consulting internship. Requires Swedish/Nordic language + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Internship - Data & Analytics - Madrid', 'internship', 'eu', 'Madrid', 'Spain', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_323473/Oliver-Wyman-Internship-Data-Analytics-Spain',
   $q$8-24 week internship in financial services/risk analytics. For penultimate-year quantitative students, requires Python/R, English/Spanish/Portuguese. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Consultant Intern - Milan', 'internship', 'eu', 'Milan', 'Italy', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_358729/Oliver-Wyman-Consultant-Intern-M-F-D-Italy',
   $q$Consulting internship for Master's students. Flexible work environment. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Intern Consultant - Amsterdam (Netherlands)', 'internship', 'eu', 'Amsterdam', 'Netherlands', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_333227/OLIVER-WYMAN-INTERN-CONSULTANT-2026-NETHERLANDS',
   $q$Consulting internship. Requires English, Dutch desirable. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Intern - Operations - Paris', 'internship', 'eu', 'Paris', 'France', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_295551/Oliver-Wyman-Intern-Operations-Paris-France',
   $q$6-month operations internship (Engineering/Procurement/Manufacturing/Supply Chain/Services Optimisation) for recent grads, with potential for a permanent role. Requires French + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Entry-level Consultant 2027 - Stockholm', 'entry_level', 'eu', 'Stockholm', 'Sweden', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_351077/Oliver-Wyman-Entry-level-Consultant-m-f-d-2027-Stockholm',
   $q$Full-time entry-level consulting graduate role. Requires Bachelor's/Master's, Swedish/Scandinavian language + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Entry-level Consultant 2027 - Copenhagen', 'entry_level', 'eu', 'Copenhagen', 'Denmark', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_351078/Oliver-Wyman-2027-Entry-level-Consultant-m-f-d-Copenhagen',
   $q$Full-time entry-level consultant graduate role. Requires Danish/Nordic language + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Entry-Level Consultant - Paris', 'entry_level', 'eu', 'Paris', 'France', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_363857/Oliver-Wyman-Entry-Level-Consultant-Paris',
   $q$Full-time entry-level consultant graduate role. Requires Master's degree, French + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Entry-Level Consultant - Brussels', 'entry_level', 'eu', 'Brussels', 'Belgium', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_364431/Oliver-Wyman-Entry-Level-Consultant-Brussels-Belgium',
   $q$Full-time entry-level consultant graduate role. Requires Bachelor's/Master's, English; travel within Belgium/internationally. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Entry-level Consultant - Spanish speaker - Madrid', 'entry_level', 'eu', 'Madrid', 'Spain', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_357756/2027-Oliver-Wyman-Entry-level-Consultant-Spanish-speaker-m-f-d-Madrid',
   $q$Full-time entry-level consultant graduate role. Requires Bachelor's, Spanish + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Entry-level Consultant - Portuguese speaker - Madrid', 'entry_level', 'eu', 'Madrid', 'Spain', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_363925/2027-Oliver-Wyman-Entry-level-Consultant-Portuguese-speaker-m-f-d-Madrid',
   $q$Full-time entry-level consultant graduate role. Requires Bachelor's, Portuguese + English. Sourced 28 Sept 2026.$q$,
   'unknown', true),
  ('Oliver Wyman', 'Core Consulting Group Entry-level Consultant - Zurich', 'entry_level', 'eu', 'Zurich', 'Switzerland', 2027, 'open',
   null, 'https://careers.marsh.com/global/en/job/R_326812/Oliver-Wyman-Core-Consulting-Group-Entry-level-Consultant-m-f-d-Zurich',
   $q$Full-time entry-level consultant engaging with corporate/government leaders. Requires Master's/PhD/MBA, German + English. Sourced 28 Sept 2026.$q$,
   'unknown', true);
