-- Opportunities added 6 Oct 2026 (part 1).
-- Founder spotted these roles on LinkedIn and asked for them to be added.
-- LinkedIn is not an acceptable source, so each role was found and verified
-- on the employer's own careers site/ATS and checked against existing rows
-- first. Where the employer's page title differed from LinkedIn's, the
-- employer's title is used. Roles that could not be verified on an employer
-- site, were no longer live, or required prior experience were left out.
-- Already applied directly to production via the Supabase admin client -
-- this file is kept for the repo's audit trail.

insert into public.opportunities
  (company, role_title, category, region, city, country, cycle_year, status,
   deadline, apply_url, notes, visa_sponsorship, is_published)
values
  ('BNP Paribas', '2027 Global Markets Graduate Analyst - Research', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/2027-global-markets-graduate-analyst-research/',
   $q$Global Markets graduate programme: 3-week EMEA induction then a direct start in the Research team (London only). Open to students completing their degree in 2027 or within two years of graduating, with a 2:1 or above. No closing date shown on the page. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London 2027 Graduate -Capital Markets- Global Banking', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-2027-graduate-capital-markets-global-banking/',
   $q$Non-rotational Global Banking graduate role embedded in the Capital Markets team. For students completing their degree in 2027 or graduates from 2025-2027. No closing date shown; only one Graduate role can be applied for per academic year. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Graduate Programme - Group Audit - Birmingham - 2027', 'grad_scheme', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   '2026-10-18', 'https://db.recsolu.com/jobs/T0wQZBne-GIsNVzEXdDrvg?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Year-long graduate programme in Group Audit (third line of defence), starting July 2027. Must complete studies between 1 Jan 2026 and 31 Jul 2027, be on track for a 2:1 or above, and have no more than 12 months full-time relevant experience. Rolling hiring, so the role may close before the deadline. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Graduate Programme - Chief Risk Office - London 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-18', 'https://db.recsolu.com/jobs/wPkxWntNQUbHi1hCr4r_KQ?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$12-month graduate programme in the Chief Risk Office starting July 2027. Must complete studies between 1 Jan 2026 and 31 Jul 2027, be on track for a 2:1 or above, and have no more than 12 months full-time relevant experience. Rolling hiring, so the role may close before the deadline. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Graduate Programme - Investment Bank & Capital Markets - UK Coverage - London - 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/fXJVEm6zxc3xxKADOzzUEQ?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Year-long graduate programme in IBCM UK Coverage starting July 2027. Must complete studies between 1 Jan 2026 and 31 Jul 2027, be on track for a 2:1 or above, and have no more than 12 months full-time relevant experience. Closes 11 Oct 2026 and may close earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('TD Securities', '2027 Graduate Programme - Investment Banking Analyst', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://td.wd3.myworkdayjobs.com/TD_Bank_Careers/job/London-United-Kingdom/XMLNAME-2027-Graduate-Programme---Investment-Banking-Analyst_R_1514179',
   $q$Full-time Analyst role with Graduate Programme in year one (starts July 2027), including one month of training in NYC; London Investment Banking, Global Energy, Power and Utilities team. Needs a 2:1 or above, 2027 graduation year (2026 may be considered), and CV plus cover letter. No closing date shown; proof of unrestricted UK right to work required before offer. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Standard Bank Group', 'Intern, Corporate & Investment Banking, International', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://jobs.smartrecruiters.com/StandardBankGroup/744000152994500-intern-corporate-investment-banking-international',
   $q$8-week Summer Internship in London (7 June - 30 July 2027) at 20 Gresham Street, with strong performers considered for the Graduate Programme. For students due to graduate in 2027 or recent graduates with a 2:1 or above and UK right to work for the full internship. Posted 1 Oct 2026, no closing date shown; posting title differs from the LinkedIn title but is the only London CIB summer intern posting. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London 2027 Technology Graduate', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-2027-technology-graduate/',
   $q$Non-rotational Technology graduate role with one team for the duration of the programme. Open to 2027 graduates and those who graduated 2025-2027. No closing date shown; only one Graduate role per academic year. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', '2027 Global Markets Graduate Analyst - Sales', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/2027-global-markets-graduate-analyst-sales/',
   $q$Global Markets graduate programme with a direct start in the Sales team (London only), after a 3-week EMEA induction. Open to students completing their degree in 2027 or within two years of graduating. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - 2027 Global Markets Graduate Analyst - Trading', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-2027-global-markets-graduate-analyst-trading/',
   $q$Global Markets graduate programme with a direct start in the Trading team (London only), after a 3-week EMEA induction. Open to students completing their degree in 2027 or within two years of graduating. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', '2027 Global Markets Graduate Analyst - Structuring', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/2027-global-markets-graduate-analyst-structuring/',
   $q$Global Markets graduate programme with a direct start in the Structuring team (London only), after a 3-week EMEA induction. Open to students completing their degree in 2027 or within two years of graduating. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London 2027 Graduate - Coverage - Global Banking', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-2027-graduate-coverage-global-banking/',
   $q$Non-rotational Global Banking graduate role embedded in a Coverage team. For students completing their degree in 2027 or graduates from 2025-2027. No closing date shown; only one Graduate role per academic year. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London 2027 Graduate -M&A- Global Banking', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-2027-graduate-ma-global-banking/',
   $q$Non-rotational Global Banking graduate role in the M&A teams (live deal execution, valuation, due diligence). For students completing their degree in 2027 or graduates from 2025-2027. No closing date shown; only one Graduate role per academic year. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Graduate Associate Programme 2027 - Automated Market Making ETF', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-graduate-associate-programme-2027-automated-market-making-etf/',
   $q$ETF Quant Trader graduate role supporting electronic market-making. Needs a STEM or Computer Science MSc and strong Python. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Graduate Associate Programme 2027 - Global Markets Quantitative Research', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-graduate-associate-programme-2027-global-markets-quantitative-research/',
   $q$Quant graduate role with a 3-week induction, then a full-time role in a Global Markets quant team (Rates, Credit, FX, Repo & Financing, Prime Services). Minimum Master's or PhD in a quantitative subject. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Quant Long Term Internship 2027 - Cash Equity Electronic Equities', 'placement_year', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-quant-long-term-internship-2027-cash-equity-electronic-equities/',
   $q$12-month long-term internship in electronic equities quant; start dates to be agreed at interview. For candidates pursuing a Master's or PhD in a quantitative subject. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Long Term Internship 2027 - Data & AI Lab', 'off_cycle', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-long-term-internship-2027-data-ai-lab/',
   $q$6-month long-term internship in the Global Markets Data & AI Lab; start dates to be agreed at interview. Needs Master's or PhD level Statistics, Maths or Computer Science, with machine learning and Python skills. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Long Term Internship 2027 - Global Markets Quantitative Research Analyst', 'off_cycle', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-long-term-internship-2027-global-markets-quantitative-research-analyst/',
   $q$6-month long-term internship in Global Markets quantitative research (pricing and market-making models); start dates to be agreed at interview. Minimum Master's or PhD in a quantitative subject. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Long Term Internship 2027 - eTrading Quantitative Research', 'off_cycle', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-long-term-internship-2027-etrading-quantitative-research/',
   $q$8-month long-term internship building algorithmic pricing and execution tools for FIC market making; start dates to be agreed at interview. Minimum Master's or PhD in a quantitative subject with strong programming. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Long Term Internship 2026 - Credit Structuring Intern', 'off_cycle', 'uk', 'London', 'United Kingdom', 2026, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-long-term-internship-2026-credit-structuring-intern/',
   $q$8-month long-term internship in Credit Structuring (term sheets, pricing runs, trade ideas); start dates to be agreed at interview. Title says 2026 but the posting is still live on the site, so check the start date. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Long Term Internship 2026 - FIC ICAT Funds Analyst - Intern', 'placement_year', 'uk', 'London', 'United Kingdom', 2026, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-long-term-internship-2026-fic-icat-funds-analyst-intern/',
   $q$18-month long-term internship in FIC ICAT, primarily hedge fund focus; start dates to be agreed at interview. Title says 2026 but the posting is still live, so check the start date. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('BNP Paribas', 'London - Long Term Internship 2026 - FICC eDistribution Sales', 'off_cycle', 'uk', 'London', 'United Kingdom', 2026, 'rolling',
   null, 'https://careers.bnpparibas.co.uk/jobs/london-long-term-internship-2026-ficc-edistribution-sales/',
   $q$11-month long-term internship in FICC eDistribution Sales (analytics, tooling and electronic client strategy); start dates to be agreed at interview. Candidates pursuing a Master's or PhD in a quantitative subject. Title says 2026 but the posting is still live, so check the start date. No closing date shown. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Graduate Programme - Technology Data & Innovation - London 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-09', 'https://db.recsolu.com/jobs/CWSzt5Ut3QoAUqn9ca__fA?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Year-long graduate programme in Technology, Data & Innovation, starting July 2027. Must complete studies between 1 Jan 2026 and 31 Jul 2027 and have no more than 12 months full-time relevant experience. Closes 9 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Graduate Programme - Investment Banking & Capital Markets - London - 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/fo7DEu3QOJTG66JacmW4bA?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Year-long graduate programme in Investment Banking & Capital Markets, starting July 2027. Must complete studies between 1 Jan 2026 and 31 Jul 2027, be on track for a 2:1 or above, and have no more than 12 months full-time relevant experience. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Internship Programme - Group Audit - Birmingham - 2027', 'internship', 'uk', 'Birmingham', 'United Kingdom', 2027, 'open',
   '2026-10-18', 'https://db.recsolu.com/jobs/3_RnwiSaN9XXeBjoxUZlzA?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Internship in Group Audit for penultimate-year students completing studies between 1 Aug 2027 and 31 Jul 2028; programme length not stated. Max 12 months full-time relevant experience. Rolling hiring, so may close before 18 Oct 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Internship Programme - Corporate Bank - London - 2027', 'internship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-18', 'https://db.recsolu.com/jobs/EsNVDtpgpUFW6Cv3PaCmFQ?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Corporate Bank internship for penultimate-year students completing studies between 1 Aug 2027 and 31 Jul 2028; programme length not stated. Max 12 months full-time relevant experience. Rolling hiring, so may close before 18 Oct 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Internship Programme - Deutsche Bank Management Consulting - London - 2027', 'internship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-18', 'https://db.recsolu.com/jobs/Vq30AE7D2mRPIkPvX-1lCQ?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$Deutsche Bank Management Consulting internship for penultimate-year students completing studies between 1 Aug 2027 and 31 Jul 2028; programme length not stated. Max 12 months full-time relevant experience. Rolling hiring, so may close before 18 Oct 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Internship Programme - Investment Banking & Capital Markets - UK Coverage - London - 2027', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/UTZlPBkbaMEeBG_Pn_V1Uw?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$9-week Summer Internship in IBCM UK Coverage for penultimate-year students completing studies between 1 Aug 2027 and 31 Jul 2028. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Internship Programme - Investment Banking & Capital Markets - Capital Markets - London - 2027', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/l4m8M2robUvo0X9v_xqNbA?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$9-week Summer Internship in IBCM Capital Markets for penultimate-year students completing studies between 1 Aug 2027 and 31 Jul 2028. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank Internship Programme - Investment Banking & Capital Markets - London - 2027', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/LfT_-o3NuRWBauJ393Re6A?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$9-week Summer Internship in Investment Banking & Capital Markets for penultimate-year students completing studies between 1 Aug 2027 and 31 Jul 2028. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank March Seasonal 6 Month Internship Programme - Investment Bank & Capital Markets - UK Coverage - London - 2027', 'off_cycle', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/GVLL1ab3dttHyujCfHgaMQ?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$6-month full-time seasonal internship (March - September 2027) in IBCM UK Coverage, for penultimate-year students seeking a long-term internship. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank March Seasonal 6 Month Internship Programme - Investment Banking & Capital Markets - Capital Markets - London - 2027', 'off_cycle', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/QR1LMGsAdVjtXjbiHEKO3w?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$6-month full-time seasonal internship (March - September 2027) in IBCM Capital Markets, for penultimate-year students seeking a long-term internship. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Deutsche Bank', 'Deutsche Bank March Seasonal 6 Month Internship Programme - Investment Banking & Capital Markets - London - 2027', 'off_cycle', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-11', 'https://db.recsolu.com/jobs/I3F2IKv-T8rAZPMXEG1_rw?job_board_id=DT5zqeU-qZM-ltrVsIvR9Q',
   $q$6-month full-time seasonal internship (March - September 2027) in Investment Banking & Capital Markets, for penultimate-year students seeking a long-term internship. Closes 11 Oct 2026, possibly earlier on rolling hiring. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Hannover Re', 'Actuarial Graduate Programme 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-10-26', 'https://jobs.hannover-re.com/job/London-Actuarial-Graduate-Programme-2027-ENG-EC3V-0BG/1370477555/',
   $q$Four-year UK graduate programme (ref 3324) based at the London office, with rotations through Biometric Research, Business Development and Corporate Actuarial; anticipated start Autumn 2027. Open to graduates and final-year students with a minimum 2:1 in a STEM subject. Posting states the application deadline is 26 October 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Steen Associates', 'Intern - London Office', 'off_cycle', 'uk', 'London', 'United Kingdom', 2026, 'rolling',
   null, 'https://www.steenassociates.com/leadership/careers/internlondon',
   $q$Rolling internship in the London office (aerospace, defence and industrials M&A advisory) for a minimum of three months with an option to extend; on-site/hybrid in London. Aimed at recent graduates; candidates must already have the right to work in the UK (no sponsorship). Apply by emailing a CV and cover letter to careers@steenassociates.com; applications are reviewed when a place opens, with no fixed start date or deadline. The employer's title is simply 'Intern' (LinkedIn labelled it 'Off-Cycle Intern'). Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Multiplex', 'Multiplex Graduate Programme UK 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'open',
   '2026-11-30', 'https://multiplex.springboard.com.au/jobtools/jncustomsearch.viewFullSingle?in_organid=18939&in_jnCounter=226700145',
   $q$Rotational construction graduate programme (Commercial, Design, Site Supervision, H&S, Planning, Building Services, Package Management) starting September 2027. Open to Construction Management/Building, Engineering, Quantity Surveying, Architecture or related degrees. Posted 5 Oct 2026, applications close 30 Nov 2026. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Lidl GB', 'Customer Insights and Loyalty Graduate Programme', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.lidl.co.uk/jobs/customer-insights-and-loyalty-graduate-programme-london-751066',
   $q$23-month fixed-term programme split between the Customer Insights and Lidl Plus teams at Lidl House, Tolworth (Surbiton), salary 40,000 GBP plus 10% London weighting. Requires a 2:2 or higher and UK work eligibility; assessment centre is 3 Dec 2026 and Lidl may close the vacancy early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Liberty Global', 'Finance Graduate', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://libertyglobal.wd3.myworkdayjobs.com/Liberty_Global_Careers/job/London/Finance-Graduate_REQ_00038671',
   $q$Three 12-month finance rotations over 3 years with fully funded CIMA, first rotation in London, salary 44,000 GBP. No closing date or start date stated on the posting (posted early Oct 2026). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Liberty Global', 'People Graduate', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://libertyglobal.wd3.myworkdayjobs.com/Liberty_Global_Careers/job/London/People-Graduate_REQ_00038674',
   $q$Two-year HR rotational programme (Strategic Planning and Transformation, Belonging and Talent Development, Reward, HR Business Partnering) with fully funded CIPD Level 7, salary 44,000 GBP. No closing date or start date stated on the posting (posted early Oct 2026). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Baker Hughes', 'ASPIRE - Finance - 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.bakerhughes.com/global/en/job/R169482/ASPIRE-Finance-2027',
   $q$Two-year rotational finance graduate programme starting January 2027; posting lists London and Aberdeen as locations. Requires a degree completed within the last 24 months and right to work without sponsorship. No closing date stated. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Amey', 'Graduate Asset Management Consultant', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.amey.co.uk/job/London-Graduate-Asset-Management-Consultant-EC4A-1AB/1369460655/',
   $q$Graduate consultant in the Asset Management Transformation team, salary 31,000 GBP, hybrid working offered, minimum 2:1 degree (preferably STEM). The posting still says start date September 2026 (likely stale text, so cycle_year 2027 is an assumption) and Amey may close it early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Assurance, Risk and Insight Supply Chain Industrial Placement', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/assurance-risk-and-insight-supply-chain-industrial-placement-in-bristol-jid-2349',
   $q$12-month supply chain placement supporting Hinkley Point C, expected to start early September 2027, salary 26,050 GBP. Open to Business, Economics, Maths, Engineering, Geography, Science or Supply Chain students. No closing date stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Chemistry Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/chemistry-industrial-placement-in-morecambe-jid-2355',
   $q$12-month placement in the Chemistry Team at Heysham 2 Power Station, salary 26,050 GBP, for Chemistry students on track for a 2:2. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Emergency Preparedness Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/emergency-preparedness-industrial-placement-in-morecambe-jid-2358',
   $q$12-month placement at Heysham 1 or Heysham 2 Power Station, salary 26,050 GBP, with a customised Emergency Preparedness training programme. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Energy Operations Industrial Placement', 'placement_year', 'uk', 'Dunbar', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/energy-operations-industrial-placement-in-dunbar-jid-2353',
   $q$12-month placement at Torness Power Station in Scotland, salary 26,050 GBP, covering safety, radiation protection and condition monitoring. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Industrial Placement - Bridgwater', 'placement_year', 'uk', 'Bridgwater', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-industrial-placement-in-bridgwater-jid-2343',
   $q$12-month on-site engineering placement at Hinkley Point C, expected to start early September 2027, salary 26,050 GBP. For Mechanical, Electrical, Civil, Construction, Nuclear, I&C, Structural, Chemical or Process Engineering students. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Industrial Placement - Morecambe', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-industrial-placement-in-morecambe-jid-2360',
   $q$12-month engineering placement at one of EDF's Heysham nuclear sites, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Industrial Placement - Dunbar', 'placement_year', 'uk', 'Dunbar', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-industrial-placement-in-dunbar-jid-2351',
   $q$12-month engineering placement at Torness Power Station in Scotland, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Environmental Safety Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/environmental-safety-industrial-placement-in-morecambe-jid-2359',
   $q$12-month placement in the Environmental Safety Group at Heysham 1 and 2 Power Stations, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Finance Industrial Placement', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/finance-industrial-placement-in-bristol-jid-2350',
   $q$12-month finance placement at EDF EPR Engineering UK supporting Hinkley Point C, expected to start early September 2027, salary 26,050 GBP. No closing date stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Information Technology Industrial Placement', 'placement_year', 'uk', 'Bridgwater', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/information-technology-industrial-placement-in-bridgwater-jid-2346',
   $q$12-month IT placement in the Technical Assurance team at Hinkley Point C, expected to start early September 2027, salary 26,050 GBP. For IT, Cyber Security, Computer Science or Software Engineering students. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Nuclear Safety Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/nuclear-safety-industrial-placement-in-morecambe-jid-2352',
   $q$12-month nuclear safety placement at the Heysham power stations, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Nuclear Systems Engineering Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/nuclear-systems-engineering-industrial-placement-in-morecambe-jid-2361',
   $q$12-month placement at Heysham 1 learning the Fuel Route process and how AGR technology operates, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Outage Industrial Placement', 'placement_year', 'uk', 'Leiston', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/outage-industrial-placement-in-leiston-jid-2363',
   $q$12-month outage management placement at Sizewell B (Leiston), salary 26,050 GBP, for Project Management, Planning or Engineering students. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Plant Efficiency Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/plant-efficiency-industrial-placement-in-morecambe-jid-2362',
   $q$12-month placement in the Operational Technical Support team at Heysham 1, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Performance Improvement Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/performance-improvement-industrial-placement-in-morecambe-jid-2356',
   $q$Placement in the Performance Improvement team at Heysham 1, salary 26,050 GBP (the posting does not state the duration, though it is listed with EDF's 12-month placements). Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Project Delivery Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/project-delivery-industrial-placement-in-morecambe-jid-2357',
   $q$12-month project engineer/project manager placement at Heysham 1, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Project Management Industrial Placement', 'placement_year', 'uk', 'Bridgwater', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/project-management-industrial-placement-in-bridgwater-jid-2345',
   $q$12-month on-site placement at the Hinkley Point C construction site and Satellite Delivery Centre, expected to start early September 2027, salary 26,050 GBP. For Project, Construction or Structural management students. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Project Planning Industrial Placement', 'placement_year', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/project-planning-industrial-placement-in-morecambe-jid-2354',
   $q$12-month placement in the Outage Planning department at Heysham 2, salary 26,050 GBP. Start date not stated; UK right to work needed (sponsorship possible but not prioritised) and security vetting applies. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'STEM Industrial Placement', 'placement_year', 'uk', 'Bridgwater', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/stem-industrial-placement-in-bridgwater-jid-2344',
   $q$12-month on-site placement at Hinkley Point C or the Satellite Delivery Centre, expected to start early September 2027, salary 26,050 GBP. Open to Science, Technology, Engineering and Maths students. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'MEH (Mechanical, Electrical & HVAC) Supply Chain Industrial Placement', 'placement_year', 'uk', 'Bridgwater', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/meh-mechanical-electrical-and-hvac-supply-chain-industrial-placement-in-bridgwater-jid-2347',
   $q$12-month supply chain placement (contract management, supplier engagement, procurement) supporting Hinkley Point C, expected to start early September 2027, salary 26,050 GBP. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Equipment Supply Chain Industrial Placement', 'placement_year', 'uk', 'Bristol', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/equipment-supply-chain-industrial-placement-in-bristol-jid-2348',
   $q$12-month equipment supply chain placement (contract management, supplier engagement, procurement) supporting Hinkley Point C, expected to start early September 2027, salary 26,050 GBP. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Maintenance Technician Apprenticeship - Morecambe', 'apprenticeship', 'uk', 'Morecambe', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-maintenance-technician-apprenticeship-in-morecambe-jid-2333',
   $q$Four-year apprenticeship (BTEC Level 3), first two years at the National College for Nuclear in Somerset then Heysham 1 or 2, starting salary 17,606 GBP. Needs five GCSEs at grade 4+ including Maths, English and two sciences; start date and closing date not stated (cycle year assumed 2027). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Maintenance Technician Apprenticeship - Leiston', 'apprenticeship', 'uk', 'Leiston', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-maintenance-technician-apprenticeship-in-leiston-jid-2332',
   $q$Four-year apprenticeship (BTEC Level 3), first two years at the National College for Nuclear in Somerset then Sizewell B, starting salary 17,606 GBP. Needs five GCSEs at grade 4+ including Maths, English and two sciences; start date and closing date not stated (cycle year assumed 2027). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Maintenance Technician Apprenticeship - Dunbar', 'apprenticeship', 'uk', 'Dunbar', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-maintenance-technician-apprenticeship-in-dunbar-jid-2331',
   $q$Four-year apprenticeship (BTEC Level 3), first two years at the National College for Nuclear in Somerset then Torness, starting salary 17,606 GBP. Needs five GCSEs at grade 4+ including Maths, English and two sciences; start date and closing date not stated (cycle year assumed 2027). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('EDF Energy', 'Engineering Maintenance Technician Apprentice', 'apprenticeship', 'uk', 'Hartlepool', 'United Kingdom', 2027, 'rolling',
   null, 'https://careers.edfenergy.com/job/engineering-maintenance-technician-apprentice-in-hartlepool-jid-2334',
   $q$Four-year apprenticeship (BTEC Level 3), first two years at the National College for Nuclear in Somerset then Hartlepool power station, starting salary 17,606 GBP. Needs five GCSEs at grade 4+ including Maths, English and two sciences; start date and closing date not stated (cycle year assumed 2027). Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Unilever', 'Unilever Industrial Placement Programme - Communications and Corporate Affairs UK', 'placement_year', 'uk', 'Kingston upon Thames', 'United Kingdom', 2027, 'rolling',
   null, 'https://unilever.wd3.myworkdayjobs.com/Unilever_Early_Careers/job/United-Kingdom/Unilever-Industrial-Placement-Programme---Communications-and-Corporate-Affairs-UK_R-1188502',
   $q$12-month industrial placement starting June 2027, hybrid (minimum 3 days a week at London Blackfriars or Kingston), salary 27,898 GBP. Rolling deadline and apply early; the Workday record shows an end date of 12 Oct 2026, so it may close very soon. Sourced 6 Oct 2026.$q$,
   'unknown', true);

-- Existing rows corrected on 6 Oct 2026.

-- Citi Commercial Banking Full Time Analyst, London: was marked closed but
-- the jobs.citi.com page is live (posted 1 Oct 2026).
update public.opportunities set status = 'rolling'
where id = '6a04c388-fdd0-4767-aada-6fced6fe38ee';

-- Houlihan Lokey real estate role: employer's page heading is
-- "Financial Analyst, Real Estate Capital Solutions, London".
update public.opportunities
set role_title = 'Financial Analyst, Real Estate Capital Solutions, London'
where apply_url ilike '%R3047%';

-- Unilever UK industrial placements: Unilever's early careers site now lists
-- only one UK role (Communications, added above); these six are gone.
update public.opportunities set status = 'closed'
where id in (
  '3d3f2894-def8-469a-83fa-a361d27a408f', -- Human Resources
  'dfcf315e-1f1c-4614-a8e5-4c64d89493c0', -- Legal
  '057ac08a-690f-429f-91eb-66513789ad1e', -- Marketing
  '846936e8-dd61-4577-8289-1862d2aaaae2', -- Sales
  '165f2acc-8e0f-4aac-a83f-6c9955683c67', -- Supply Chain Non-Technical
  'ac5afd81-c31c-48ce-937b-09c16867a3a1'  -- Supply Chain Technical
);

-- BNP Paribas London summer internships and Women in Trading Academy: pages
-- now redirect to the early careers home page.
update public.opportunities set status = 'closed'
where id in (
  'e033505e-ee84-4c9f-aa35-5b8deca856a9', -- Coverage - Global Banking
  'a09c8780-6d43-4c5d-bbe1-bf453c199d9b', -- Technology
  'a08ab350-70b3-4ac5-acef-1c06d4a8131b', -- Global Markets
  'ceb71113-30b3-4b99-9846-fa260dad9795', -- M&A - Global Banking
  '2be826a2-7cd0-44ab-98fb-459006fb1c28', -- Capital Markets - Global Banking
  'f03aaac5-c14e-407e-b6aa-a9322a67e611'  -- Women in Trading Academy
);
