-- New opportunities added 6 Oct 2026.
-- Founder said Citi had opened new early-career roles. Citi had 16 rows
-- tracked (mostly London). Pulled the full live listing from jobs.citi.com
-- (3,107 postings, all pages) and found 83 new UK/EU/US early-career
-- postings across ~15 countries: summer analyst/associate programmes,
-- placement/off-cycle analyst internships, full-time analyst programmes,
-- and one Early ID programme with a hard deadline (23 Oct 2026). Every
-- posting says "rolling basis" except that one. No posting offers visa
-- sponsorship (US and Warsaw roles say so explicitly).
-- Excluded: APAC/Middle East/Africa/LatAm roles (platform scope), 3
-- Canadian roles, an Operations Full Time Analyst Warsaw posting titled
-- "2026" (unclear if stale), and borderline experienced/entry-level hires.
-- Also confirmed 3 existing London rows are no longer on jobs.citi.com
-- (page returns "Job Not Found") and marked them closed - see the update
-- statement at the end.
-- Already applied directly to production via the Supabase admin client -
-- this file is kept for the repo's audit trail.

insert into public.opportunities
  (company, role_title, category, region, city, country, cycle_year, status,
   deadline, apply_url, notes, visa_sponsorship, is_published)
values
  ('Citi', 'Banking, Investment Banking, Summer Analyst, London - United Kingdom 2027', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/london/banking-investment-banking-summer-analyst-london-united-kingdom-2027/287/100315643136',
   $q$Citi summer programme in London: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. No application deadline stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Real Estate, Summer Analyst, London, United Kingdom 2027', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/london/banking-investment-banking-real-estate-summer-analyst-london-united-kingdom-2027/287/101406622800',
   $q$Citi summer programme in London: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Hybrid working model. No application deadline stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking - Financial Institution Group (FIG), Summer Analyst, London, United Kingdom 2027', 'summer_internship', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/london/banking-investment-banking-financial-institution-group-fig-summer-analyst-london-united-kingdom-2027/287/101406622384',
   $q$Citi summer programme in London: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. No application deadline stated. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Markets - Sales and Trading, Full Time Analyst, London - United Kingdom, 2027', 'grad_scheme', 'uk', 'London', 'United Kingdom', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/london/markets-sales-and-trading-full-time-analyst-london-united-kingdom-2027/287/100186099392',
   $q$Citi full-time graduate analyst programme in London, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Chief Operating Office - Full-Time Analyst, UK - Belfast, 2027', 'grad_scheme', 'uk', 'Belfast', 'United Kingdom', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/belfast/chief-operating-office-full-time-analyst-uk-belfast-2027/287/101576414544',
   $q$Citi full-time graduate analyst programme in Belfast, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking - Investment Banking, Full Time Analyst, Frankfurt, Germany 2027', 'grad_scheme', 'eu', 'Frankfurt', 'Germany', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/banking-investment-banking-full-time-analyst-frankfurt-germany-2027/287/101350228368',
   $q$Citi full-time graduate analyst programme in Frankfurt, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Full Time Analyst, Frankfurt - Germany 2027', 'grad_scheme', 'eu', 'Frankfurt', 'Germany', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/banking-commercial-banking-full-time-analyst-frankfurt-germany-2027/287/101091476720',
   $q$Citi full-time graduate analyst programme in Frankfurt, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Summer Analyst, Frankfurt - Germany 2027', 'summer_internship', 'eu', 'Frankfurt', 'Germany', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/banking-commercial-banking-summer-analyst-frankfurt-germany-2027/287/100661681296',
   $q$Citi summer programme in Frankfurt: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Markets - Sales, Trading & Structuring, Off-Cycle Internship, Frankfurt - Germany, 2026', 'off_cycle', 'eu', 'Frankfurt', 'Germany', 2026, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/markets-sales-trading-and-structuring-off-cycle-internship-frankfurt-germany-2026/287/101320624672',
   $q$Citi placement/off-cycle analyst internship in Frankfurt, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Debt Capital Markets, Placement Analyst Internship, Frankfurt - Germany 2027', 'off_cycle', 'eu', 'Frankfurt', 'Germany', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/banking-debt-capital-markets-placement-analyst-internship-frankfurt-germany-2027/287/100709897024',
   $q$Citi placement/off-cycle analyst internship in Frankfurt, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Financing, Equity Capital Markets Placement Analyst Internship, Frankfurt - Germany 2027', 'off_cycle', 'eu', 'Frankfurt', 'Germany', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/banking-financing-equity-capital-markets-placement-analyst-internship-frankfurt-germany-2027/287/100178760848',
   $q$Citi placement/off-cycle analyst internship in Frankfurt, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Placement Analyst Internship, Frankfurt - Germany 2027', 'off_cycle', 'eu', 'Frankfurt', 'Germany', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/frankfurt-am-main/banking-corporate-banking-placement-analyst-internship-frankfurt-germany-2027/287/100164759200',
   $q$Citi placement/off-cycle analyst internship in Frankfurt, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. 3 months or more, any start date in 2027. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Relationship Analyst, Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-corporate-banking-relationship-analyst-placement-analyst-internship-paris-france-2027/287/101320593040',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Financial Institutions Group (FIG), Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-corporate-banking-financial-institutions-group-fig-placement-analyst-internship-paris-franc/287/100709896848',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-corporate-banking-placement-analyst-internship-paris-france-2027/287/100295995168',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-investment-banking-placement-analyst-internship-paris-france-2027/287/100164759312',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Financial Institution Group, Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-investment-banking-financial-institution-group-placement-analyst-internship-paris-france-20/287/100164759248',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Financing, Equity Capital Markets, Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-financing-equity-capital-markets-placement-analyst-internship-paris-france-2027/287/100308124400',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Financing, Debt Capital Markets, Placement Analyst Internship, Paris - France 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-financing-debt-capital-markets-placement-analyst-internship-paris-france-2027/287/100308124304',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, about 6 months. Requires student status and a visa covering the whole internship period. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Markets - Sales and Trading, Off-Cycle Internship, Paris - France, 2027', 'off_cycle', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/markets-sales-and-trading-off-cycle-internship-paris-france-2027/287/100186099504',
   $q$Citi placement/off-cycle analyst internship in Paris, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Requires a valid resident or work permit. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Full Time Analyst, Paris - France, 2027 - January Start', 'grad_scheme', 'eu', 'Paris', 'France', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/paris/banking-corporate-banking-full-time-analyst-paris-france-2027-january-start/287/100981237392',
   $q$Citi full-time graduate analyst programme in Paris, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. January 2027 start. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Placement Analyst, Madrid - Spain 2027', 'off_cycle', 'eu', 'Madrid', 'Spain', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/madrid/banking-investment-banking-placement-analyst-madrid-spain-2027/287/101091477392',
   $q$Citi placement/off-cycle analyst internship in Madrid, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, 6 months. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Full Time Analyst, Madrid - Spain 2027', 'grad_scheme', 'eu', 'Madrid', 'Spain', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/madrid/banking-commercial-banking-full-time-analyst-madrid-spain-2027/287/100981236800',
   $q$Citi full-time graduate analyst programme in Madrid, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Summer Analyst, Milan - Italy 2027', 'summer_internship', 'eu', 'Milan', 'Italy', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/milano/banking-commercial-banking-summer-analyst-milan-italy-2027/287/100661681344',
   $q$Citi summer programme in Milan: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Placement Analyst Internship, Milan - Italy 2027', 'off_cycle', 'eu', 'Milan', 'Italy', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/milano/banking-investment-banking-placement-analyst-internship-milan-italy-2027/287/100479480752',
   $q$Citi placement/off-cycle analyst internship in Milan, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Financial Institution Group, Placement Analyst, Milan, Italy 2026 - November Intake', 'off_cycle', 'eu', 'Milan', 'Italy', 2026, 'rolling',
   null, 'https://jobs.citi.com/job/milano/banking-investment-banking-financial-institution-group-placement-analyst-milan-italy-2026-november-/287/100339366192',
   $q$Citi placement/off-cycle analyst internship in Milan, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. November 2026 intake. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Relationship Analyst, Placement Analyst Internship, Milan - Italy 2027', 'off_cycle', 'eu', 'Milan', 'Italy', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/milano/banking-corporate-banking-relationship-analyst-placement-analyst-internship-milan-italy-2027/287/100164759216',
   $q$Citi placement/off-cycle analyst internship in Milan, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Full Time Analyst, Amsterdam - Netherlands, 2027', 'grad_scheme', 'eu', 'Amsterdam', 'Netherlands', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/amsterdam/banking-corporate-banking-full-time-analyst-amsterdam-netherlands-2027/287/101562619744',
   $q$Citi full-time graduate analyst programme in Amsterdam, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Starts mid-July 2027. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Summer Analyst, Amsterdam - The Netherlands 2027', 'summer_internship', 'eu', 'Amsterdam', 'Netherlands', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/amsterdam/banking-commercial-banking-summer-analyst-amsterdam-the-netherlands-2027/287/101258664464',
   $q$Citi summer programme in Amsterdam: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Summer Analyst, Amsterdam - The Netherlands, 2027', 'summer_internship', 'eu', 'Amsterdam', 'Netherlands', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/amsterdam/banking-corporate-banking-summer-analyst-amsterdam-the-netherlands-2027/287/100996355280',
   $q$Citi summer programme in Amsterdam: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Placement Analyst, Amsterdam - The Netherlands, 2027 (January- June Start)', 'off_cycle', 'eu', 'Amsterdam', 'Netherlands', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/amsterdam/banking-corporate-banking-placement-analyst-amsterdam-the-netherlands-2027-january-june-start/287/100996355216',
   $q$Citi placement/off-cycle analyst internship in Amsterdam, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. 3-6 months, January-June start. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Placement Analyst, Amsterdam - Netherlands 2027', 'off_cycle', 'eu', 'Amsterdam', 'Netherlands', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/amsterdam/banking-investment-banking-placement-analyst-amsterdam-netherlands-2027/287/100675063072',
   $q$Citi placement/off-cycle analyst internship in Amsterdam, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. Starts January 2027, up to 6 months. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Full Time Analyst, Stockholm - Sweden 2027', 'grad_scheme', 'eu', 'Stockholm', 'Sweden', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/stockholm/banking-investment-banking-full-time-analyst-stockholm-sweden-2027/287/101608149216',
   $q$Citi full-time graduate analyst programme in Stockholm, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Fluency in a Nordic language required. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Summer Analyst, Stockholm - Sweden 2027', 'summer_internship', 'eu', 'Stockholm', 'Sweden', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/stockholm/banking-commercial-banking-summer-analyst-stockholm-sweden-2027/287/101044063472',
   $q$Citi summer programme in Stockholm: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Commercial Banking, Full Time Analyst, Stockholm - Sweden 2027', 'grad_scheme', 'eu', 'Stockholm', 'Sweden', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/stockholm/banking-commercial-banking-full-time-analyst-stockholm-sweden-2027/287/101044063344',
   $q$Citi full-time graduate analyst programme in Stockholm, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Starts July 2027. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Placement Analyst, Stockholm - Sweden, 2027 - March Start', 'off_cycle', 'eu', 'Stockholm', 'Sweden', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/stockholm/banking-corporate-banking-placement-analyst-stockholm-sweden-2027-march-start/287/100683557968',
   $q$Citi placement/off-cycle analyst internship in Stockholm, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. March 2027 start. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking - Investment Banking, Placement Analyst, Stockholm - Sweden, 2027 - January and July Intake', 'off_cycle', 'eu', 'Stockholm', 'Sweden', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/stockholm/banking-investment-banking-placement-analyst-stockholm-sweden-2027-january-and-july-intake/287/100444744912',
   $q$Citi placement/off-cycle analyst internship in Stockholm, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. January and July intakes. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Investment Banking, Placement Analyst, Zurich, Switzerland 2027 - January Intake', 'off_cycle', 'eu', 'Zurich', 'Switzerland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/zurich/banking-investment-banking-placement-analyst-zurich-switzerland-2027-january-intake/287/101406622784',
   $q$Citi placement/off-cycle analyst internship in Zurich, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. 4-6 months from January 2027. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Summer Analyst, Zurich - Switzerland, 2027', 'summer_internship', 'eu', 'Zurich', 'Switzerland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/zurich/banking-corporate-banking-summer-analyst-zurich-switzerland-2027/287/101004948832',
   $q$Citi summer programme in Zurich: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Citi Global Wealth, Summer Analyst, Geneva - Switzerland, 2027', 'summer_internship', 'eu', 'Geneva', 'Switzerland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/geneva/citi-global-wealth-summer-analyst-geneva-switzerland-2027/287/101076875904',
   $q$Citi summer programme in Geneva: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Citi Global Wealth, Summer Analyst, Bertrange - Luxembourg 2027', 'summer_internship', 'eu', 'Bertrange', 'Luxembourg', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/bertrange/citi-global-wealth-summer-analyst-bertrange-luxembourg-2027/287/101076875888',
   $q$Citi summer programme in Bertrange: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Placement Analyst, Copenhagen - Denmark, 2027 - January Start', 'off_cycle', 'eu', 'Copenhagen', 'Denmark', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/copenhagen/banking-corporate-banking-placement-analyst-copenhagen-denmark-2027-january-start/287/101451411056',
   $q$Citi placement/off-cycle analyst internship in Copenhagen, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. January 2027 start. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Banking, Corporate Banking, Placement Analyst, Helsinki - Finland, 2027 - March Start', 'off_cycle', 'eu', 'Helsinki', 'Finland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/finland/banking-corporate-banking-placement-analyst-helsinki-finland-2027-march-start/287/101044063824',
   $q$Citi placement/off-cycle analyst internship in Helsinki, typically 3-6 months from January 2027 (exact start varies by role), working as an analyst in the named team. Rolling applications - apply early. March 2027 start. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Services - Summer Analyst, Ireland - Dublin, 2027', 'summer_internship', 'eu', 'Dublin', 'Ireland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/dublin/services-summer-analyst-ireland-dublin-2027/287/101076934336',
   $q$Citi summer programme in Dublin: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Services - Full-Time Analyst, Ireland - Dublin, 2027 (2026 Summer Intern Converts Only)', 'grad_scheme', 'eu', 'Dublin', 'Ireland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/dublin/services-full-time-analyst-ireland-dublin-2027-2026-summer-intern-converts-only/287/100771374000',
   $q$Citi full-time graduate analyst programme in Dublin, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Open to 2026 Citi summer interns only. Sourced 6 Oct 2026.$q$,
   'unknown', true),
  ('Citi', 'Technology - Cyber Security, Summer Analyst, Warsaw 2027', 'summer_internship', 'eu', 'Warsaw', 'Poland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/warsaw/technology-cyber-security-summer-analyst-warsaw-2027/287/101406692848',
   $q$Citi summer programme in Warsaw: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Requires authorisation to work in Poland without employer sponsorship. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Technology - Infrastructure, Summer Analyst, Warsaw 2027', 'summer_internship', 'eu', 'Warsaw', 'Poland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/warsaw/technology-infrastructure-summer-analyst-warsaw-2027/287/101394354736',
   $q$Citi summer programme in Warsaw: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Requires authorisation to work in Poland without employer sponsorship. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Internal Audit - Summer Analyst, Warsaw, 2027', 'summer_internship', 'eu', 'Warsaw', 'Poland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/warsaw/internal-audit-summer-analyst-warsaw-2027/287/101044085296',
   $q$Citi summer programme in Warsaw: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Requires authorisation to work in Poland without employer sponsorship. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Risk - Full-Time Analyst, Warsaw, 2027 - (Applicable for 2026 Citi Summer interns only)', 'grad_scheme', 'eu', 'Warsaw', 'Poland', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/warsaw/risk-full-time-analyst-warsaw-2027-applicable-for-2026-citi-summer-interns-only/287/101275130768',
   $q$Citi full-time graduate analyst programme in Warsaw, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Open to 2026 Citi summer interns only. Requires authorisation to work in Poland without employer sponsorship. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Investment Banking, Summer Associate, New York (North America - 2027)', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/banking-investment-banking-summer-associate-new-york-north-america-2027/287/101451410192',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Investment Banking, Summer Associate, San Francisco Technology (North America - 2027)', 'summer_internship', 'us', 'San Francisco', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/san-francisco/banking-investment-banking-summer-associate-san-francisco-technology-north-america-2027/287/101451410256',
   $q$Citi summer programme in San Francisco: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Investment Banking, Summer Associate, San Francisco Healthcare (North America - 2027)', 'summer_internship', 'us', 'San Francisco', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/san-francisco/banking-investment-banking-summer-associate-san-francisco-healthcare-north-america-2027/287/101451410208',
   $q$Citi summer programme in San Francisco: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Investment Banking, Summer Associate, Houston Energy (North America - 2027)', 'summer_internship', 'us', 'Houston', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/houston/banking-investment-banking-summer-associate-houston-energy-north-america-2027/287/101451410160',
   $q$Citi summer programme in Houston: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Investment Banking, Summer Associate, Chicago (North America - 2027)', 'summer_internship', 'us', 'Chicago', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/chicago/banking-investment-banking-summer-associate-chicago-north-america-2027/287/101451410144',
   $q$Citi summer programme in Chicago: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Investment Banking, Latin America Group Summer Associate, New York (North America - 2027)', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/banking-investment-banking-latin-america-group-summer-associate-new-york-north-america-2027/287/101451409984',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Capital Markets, Summer Associate, New York (North America - 2027)', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/banking-capital-markets-summer-associate-new-york-north-america-2027/287/101451409520',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Corporate Banking, Summer Analyst, Atlanta - US, 2027', 'summer_internship', 'us', 'Atlanta', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/atlanta/banking-corporate-banking-summer-analyst-atlanta-us-2027/287/100637178976',
   $q$Citi summer programme in Atlanta: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Corporate Banking, Summer Analyst, Houston - US, 2027', 'summer_internship', 'us', 'Houston', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/houston/banking-corporate-banking-summer-analyst-houston-us-2027/287/89623966960',
   $q$Citi summer programme in Houston: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Banking - Commercial Banking - Natural Resources & Energy, Summer Analyst, Houston - US, 2027', 'summer_internship', 'us', 'Houston', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/houston/banking-commercial-banking-natural-resources-and-energy-summer-analyst-houston-us-2027/287/89631582048',
   $q$Citi summer programme in Houston: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Markets - Quantitative Analysis, Summer Analyst - New York City - US, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/markets-quantitative-analysis-summer-analyst-new-york-city-us-2027/287/89809477472',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Services - Summer Analyst Program, New York City - US, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/services-summer-analyst-program-new-york-city-us-2027/287/93724104768',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Enterprise Services and Public Affairs, Summer Analyst, New York - USA, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/functions-enterprise-services-and-public-affairs-summer-analyst-new-york-usa-2027/287/101320607984',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Finance, Summer Associate, New York - USA, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/functions-finance-summer-associate-new-york-usa-2027/287/101328061424',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Finance, Summer Associate, Tampa - USA, 2027', 'summer_internship', 'us', 'Tampa', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/tampa/functions-finance-summer-associate-tampa-usa-2027/287/101370853136',
   $q$Citi summer programme in Tampa: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Internal Audit, Summer Analyst, New York - USA, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/functions-internal-audit-summer-analyst-new-york-usa-2027/287/98836136896',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Internal Audit, Summer Analyst, Tampa - USA, 2027', 'summer_internship', 'us', 'Tampa', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/tampa/functions-internal-audit-summer-analyst-tampa-usa-2027/287/93639707152',
   $q$Citi summer programme in Tampa: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Internal Audit, Summer Analyst, Dallas - USA, 2027', 'summer_internship', 'us', 'Dallas', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/irving/functions-internal-audit-summer-analyst-dallas-usa-2027/287/93639707136',
   $q$Citi summer programme in Dallas: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Listed under Irving, TX. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Risk Management, Summer Analyst, Irving - USA, 2027', 'summer_internship', 'us', 'Irving', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/irving/functions-risk-management-summer-analyst-irving-usa-2027/287/94188563584',
   $q$Citi summer programme in Irving: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Risk Management, Summer Analyst, Buffalo - USA, 2027', 'summer_internship', 'us', 'Buffalo', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/getzville/functions-risk-management-summer-analyst-buffalo-usa-2027/287/94188563568',
   $q$Citi summer programme in Buffalo: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Listed under Getzville, NY. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Risk Management, Summer Analyst, Tampa - USA, 2027', 'summer_internship', 'us', 'Tampa', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/tampa/functions-risk-management-summer-analyst-tampa-usa-2027/287/100084224112',
   $q$Citi summer programme in Tampa: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Chief Operating Office, Summer Analyst, Tampa - USA, 2027', 'summer_internship', 'us', 'Tampa', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/tampa/functions-chief-operating-office-summer-analyst-tampa-usa-2027/287/100084223904',
   $q$Citi summer programme in Tampa: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Wealth - Summer Analyst, New York - USA, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/wealth-summer-analyst-new-york-usa-2027/287/100661745184',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Runs June to August. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Wealth - Summer Analyst, Miami - USA, 2027', 'summer_internship', 'us', 'Miami', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/miami/wealth-summer-analyst-miami-usa-2027/287/100661745168',
   $q$Citi summer programme in Miami: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Wealth - Summer Analyst, Los Angeles - USA, 2027', 'summer_internship', 'us', 'Los Angeles', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/beverly-hills/wealth-summer-analyst-los-angeles-usa-2027/287/100661745152',
   $q$Citi summer programme in Los Angeles: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Listed under Beverly Hills, CA. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Wealth - Summer Analyst, Dallas - USA, 2027', 'summer_internship', 'us', 'Dallas', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/dallas/wealth-summer-analyst-dallas-usa-2027/287/100661745120',
   $q$Citi summer programme in Dallas: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Wealth - LATAM, Summer Analyst, New York - USA, 2027', 'summer_internship', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/wealth-latam-summer-analyst-new-york-usa-2027/287/100661744992',
   $q$Citi summer programme in New York: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Wealth - LATAM, Summer Analyst, Miami - USA, 2027', 'summer_internship', 'us', 'Miami', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/miami/wealth-latam-summer-analyst-miami-usa-2027/287/100661744944',
   $q$Citi summer programme in Miami: roughly 10 weeks from June 2027, starting with a training week and then placement in a team; strong performers are considered for a full-time offer. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Finance, Full Time Associate, New York - USA, 2027', 'grad_scheme', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/functions-finance-full-time-associate-new-york-usa-2027/287/101328061408',
   $q$Citi full-time graduate analyst programme in New York, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. For graduates finishing between Dec 2026 and Jun 2027. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Finance, Full Time Associate, Tampa - USA, 2027', 'grad_scheme', 'us', 'Tampa', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/tampa/functions-finance-full-time-associate-tampa-usa-2027/287/101370853104',
   $q$Citi full-time graduate analyst programme in Tampa, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'U.S. Consumer Cards - Full-Time Analyst, New York - USA, 2027', 'grad_scheme', 'us', 'New York', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/new-york/u-s-consumer-cards-full-time-analyst-new-york-usa-2027/287/100133567712',
   $q$Citi full-time graduate analyst programme in New York, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Internal Audit, Full-Time Analyst, Tampa - USA, 2027', 'grad_scheme', 'us', 'Tampa', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/tampa/functions-internal-audit-full-time-analyst-tampa-usa-2027/287/98534966992',
   $q$Citi full-time graduate analyst programme in Tampa, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Functions - Internal Audit, Full-Time Analyst, Dallas - USA, 2027', 'grad_scheme', 'us', 'Dallas', 'United States', 2027, 'rolling',
   null, 'https://jobs.citi.com/job/irving/functions-internal-audit-full-time-analyst-dallas-usa-2027/287/98534966928',
   $q$Citi full-time graduate analyst programme in Dallas, typically starting July 2027, with in-depth training before team placement. Rolling applications - apply early. Listed under Irving, TX. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true),
  ('Citi', 'Early ID Program - Investment Banking, Fall 2026 - San Francisco Healthcare', 'insight_program', 'us', 'San Francisco', 'United States', 2027, 'open',
   '2026-10-23', 'https://jobs.citi.com/job/san-francisco/early-id-program-investment-banking-fall-2026-san-francisco-healthcare/287/101576426736',
   $q$Early identification programme (not a summer internship) for Investment Banking, San Francisco Healthcare group, Fall 2026. Applications close 23 Oct 2026, 11:59pm ET. The posting gives few other details. Citi will not sponsor US work authorisation for this role. Sourced 6 Oct 2026.$q$,
   'no', true);

-- Existing rows confirmed delisted from jobs.citi.com on 6 Oct 2026.
update public.opportunities
set status = 'closed'
where id in (
  '62dda1fe-7c18-48fe-b824-8ba34b6a2e92', -- Corporate Banking, Summer Analyst, London 2027
  '163f5e8a-24c2-4d57-ae7f-ada6a09b6ed9', -- Markets - Sales and Trading, Summer Analyst, London 2027
  'c78b69af-ae7c-4b4a-a34a-3d3484ed99af'  -- Corporate Banking, Placement Analyst, London 2027
);
