-- MUFG cleanup, 6 Oct 2026.
-- Why: the nightly discover-opportunities job only read the first 1,000 existing
-- rows, so it re-inserted already-known postings as new unpublished drafts every
-- night, and its "intern" substring match also drafted senior "Internal Audit"
-- roles. MUFG had 79 hidden drafts (category 'other', cycle 2026, no city) made
-- of 41 distinct postings, plus 12 curated published rows.
-- What was done (already applied via the Supabase admin client):
--   1. Each live UK/EU/US early-career posting (confirmed on MUFG's own Workday
--      job system) kept ONE draft row, which was corrected and published (below).
--   2. All other MUFG drafts were deleted: extra copies of the same posting,
--      postings already published, removed postings (6 UK apprenticeship
--      postings, 1 US intern-conversion role), non-UK/EU/US offices (Hong Kong,
--      Jakarta, Mumbai, Bengaluru, Turkey), and false positives such as
--      "VP - Internal Audit" and "Internal Communications and PA to CFO".
--      67 rows; no application or link-click referenced any of them.
--   3. One published insight event no longer on MUFG's site was closed.
-- Run order matters: the corrections come first, then the delete.

update public.opportunities set role_title = '2027 MUFG 6 month Amsterdam internship: Japanese Corporate Banking Division', category = 'off_cycle', region = 'eu', city = 'Amsterdam', country = 'Netherlands', cycle_year = 2027, status = 'open', deadline = '2026-11-15', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/Amsterdam/XMLNAME-2027-MUFG-6-month-Amsterdam-internship--Japanese-Corporate-Banking-Division_10079926-WD', notes = '6-month internship in MUFG''s Japanese Corporate Banking Division, Amsterdam, working with colleagues across MUFG''s global network including Japan. Applications close 15 Nov 2026. Sourced 6 Oct 2026.', is_published = true where id = 'e53a93f3-5ea3-47c0-be7c-2177bbb58542';
update public.opportunities set role_title = '2027 MUFG 6 month Milan internship: Japanese Corporate Banking Division', category = 'off_cycle', region = 'eu', city = 'Milan', country = 'Italy', cycle_year = 2027, status = 'open', deadline = '2026-11-15', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/Italy/Japanese-Corporate-Banking-Division-Intern_10079940-WD', notes = '6-month internship in MUFG''s Japanese Corporate Banking Division, Milan, working with colleagues across MUFG''s global network including Japan. Applications close 15 Nov 2026. Sourced 6 Oct 2026.', is_published = true where id = 'f79ee1c2-313b-4728-be5d-51e60bd32992';
update public.opportunities set role_title = '2027 MUFG 6-Month Early Careers Placement - Germany', category = 'off_cycle', region = 'eu', city = 'Dusseldorf', country = 'Germany', cycle_year = 2027, status = 'open', deadline = '2026-11-01', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/Duesseldorf/XMLNAME-2027-MUFG-6-Month-Early-Careers-Placement---Germany_10079947-WD-1', notes = '6-month early careers placement at MUFG in Dusseldorf, working with colleagues across MUFG''s global network including Japan. Applications close 1 Nov 2026. Sourced 6 Oct 2026.', is_published = true where id = '965aaf7c-1aa0-4e82-864a-05a041979660';
update public.opportunities set role_title = '2027 MUFG UK Summer Analyst Programme: Capital Markets', category = 'summer_internship', region = 'uk', city = 'London', country = 'United Kingdom', cycle_year = 2027, status = 'open', deadline = '2026-11-29', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2027-MUFG-UK-Summer-Analyst-Programme--Capital-Markets_10079265-WD-1', notes = 'Summer analyst programme in MUFG''s Capital Markets team, London. Applications close 29 Nov 2026; assessment centre Feb 2027; programme starts 21 June 2027. Sourced 6 Oct 2026.', is_published = true where id = '839fea3e-359e-4c45-9427-d4ab14b309b5';
update public.opportunities set role_title = '2027 MUFG UK Summer Analyst Programme: Credit Sales and Trading', category = 'summer_internship', region = 'uk', city = 'London', country = 'United Kingdom', cycle_year = 2027, status = 'open', deadline = '2026-11-29', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2027-MUFG-UK-Summer-Analyst-Programme--Credit-Sales-and-Trading_10079355-WD-1', notes = 'Summer analyst programme in MUFG''s Credit Sales and Trading team, London. Applications close 29 Nov 2026; assessment centre Feb 2027; programme starts 21 June 2027. Sourced 6 Oct 2026.', is_published = true where id = '32e1ee79-4ea1-4042-830c-911dede4af41';
update public.opportunities set role_title = '2027 MUFG UK Summer Analyst Programme: Global Client Sales', category = 'summer_internship', region = 'uk', city = 'London', country = 'United Kingdom', cycle_year = 2027, status = 'open', deadline = '2026-11-29', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2027-MUFG-UK-Summer-Analyst-Programme--Global-Client-Sales_10079834-WD', notes = 'Summer analyst programme in MUFG''s Global Client Sales team, London. Applications close 29 Nov 2026; assessment centre Feb 2027; programme starts 21 June 2027. Sourced 6 Oct 2026.', is_published = true where id = '594eeea9-519b-4ed3-86b7-8d3970edc7fc';
update public.opportunities set role_title = '2027 MUFG UK Summer Analyst Programme: Global Corporate Investment Banking', category = 'summer_internship', region = 'uk', city = 'London', country = 'United Kingdom', cycle_year = 2027, status = 'open', deadline = '2026-11-29', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2027-MUFG-UK-Summer-Analyst-Programme--Global-Corporate-Investment-Banking_10079259-WD-1', notes = 'Summer analyst programme in MUFG''s Global Corporate Investment Banking coverage team, London. Applications close 29 Nov 2026; assessment centre Feb 2027; programme starts 21 June 2027. Sourced 6 Oct 2026.', is_published = true where id = '30e107cf-9074-4ae5-9d0d-be84b84b9313';
update public.opportunities set role_title = '2027 MUFG UK Summer Analyst Programme: Japanese Corporate Banking', category = 'summer_internship', region = 'uk', city = 'London', country = 'United Kingdom', cycle_year = 2027, status = 'open', deadline = '2026-11-29', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2027-MUFG-UK-Summer-Analyst-Programme--Japanese-Corporate-Banking_10079266-WD-1', notes = 'Summer analyst programme in MUFG''s Japanese Corporate Banking team, London. Applications close 29 Nov 2026; assessment centre Feb 2027; programme starts 21 June 2027. Sourced 6 Oct 2026.', is_published = true where id = '67eea3eb-68dd-4e51-8a36-b97156792fc7';
update public.opportunities set role_title = '2027 MUFG UK Summer Analyst Programme: Structured Trading Group', category = 'summer_internship', region = 'uk', city = 'London', country = 'United Kingdom', cycle_year = 2027, status = 'open', deadline = '2026-11-29', apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2027-MUFG-UK-Summer-Analyst-Programme--Structured-Trading-Group_10079356-WD-1', notes = 'Summer analyst programme in MUFG''s Structured Trading Group, London. Applications close 29 Nov 2026; assessment centre Feb 2027; programme starts 21 June 2027. Sourced 6 Oct 2026.', is_published = true where id = 'cf532326-ff32-4139-b47e-62fef5081372';
update public.opportunities set role_title = '2027 Operations Summer Analyst Program - Tampa, FL', category = 'summer_internship', region = 'us', city = 'Tampa', country = 'United States', cycle_year = 2027, status = 'rolling', deadline = null, apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/Tampa-FL/XMLNAME-2027-Operation-Summer-Analyst-Program---Tampa--FL_10079128-WD-1', notes = 'Operations Summer Analyst Program 2027 in Tampa, FL: supports loan settlement and servicing, ledger reconciliation and invoicing alongside relationship and portfolio managers. No closing date stated on the posting. Sourced 6 Oct 2026.', is_published = true where id = '05a8d018-70c3-478f-b1fa-da4f3c345b2b';
update public.opportunities set role_title = '2027 Operations Summer Analyst Program - Tempe, AZ', category = 'summer_internship', region = 'us', city = 'Tempe', country = 'United States', cycle_year = 2027, status = 'rolling', deadline = null, apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/Tempe-AZ/XMLNAME-2027-Operations-Summer-Analyst-Program---Tempe--AZ_10079130-WD-1', notes = 'Operations Summer Analyst Program 2027 in Tempe, AZ: supports loan settlement and servicing, ledger reconciliation and invoicing alongside relationship and portfolio managers. No closing date stated on the posting. Sourced 6 Oct 2026.', is_published = true where id = 'de8ae43c-48ea-4ddf-9307-04314cefba4c';
update public.opportunities set role_title = '6 months internship - Stagiaire Direction Juridique/Legal Counsel Internship - January 2027', category = 'off_cycle', region = 'eu', city = 'Paris', country = 'France', cycle_year = 2027, status = 'rolling', deadline = null, apply_url = 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/Paris/XMLNAME-6-months-internship---Stagiaire-Direction-Juridique-Legal-Counsel-Internship---January-2027_10079577-WD-1', notes = '6-month legal counsel internship (Stagiaire Direction Juridique) in MUFG''s Paris office, starting January 2027. No closing date stated on the posting. Sourced 6 Oct 2026.', is_published = true where id = '7fd3f0c6-f2e8-4c73-be56-6473d09fd690';

-- Remove the remaining hidden MUFG drafts (67 rows).
delete from public.opportunities where company = 'MUFG' and is_published = false;

-- Insight event no longer listed on MUFG's careers site.
update public.opportunities set status = 'closed' where id = 'e801b530-49c5-4415-87a6-21cd56c97eb1';
